load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "collector",
    srcs = [
        "logging.go",
        "vsphere.go",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/pkg/collector",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/models",
        "//pkg/vmware",
        "@com_github_go_logr_logr//:go_default_library",
        "@com_github_kubev2v_forklift//pkg/apis/forklift/v1beta1:go_default_library",
        "@com_github_kubev2v_forklift//pkg/controller/provider/container/vsphere:go_default_library",
        "@com_github_kubev2v_forklift//pkg/controller/provider/model:go_default_library",
        "@com_github_kubev2v_forklift//pkg/controller/provider/web:go_default_library",
        "@com_github_kubev2v_forklift//pkg/controller/provider/web/base:go_default_library",
        "@com_github_kubev2v_forklift//pkg/controller/provider/web/vsphere:go_default_library",
        "@com_github_kubev2v_forklift//pkg/lib/inventory/container:go_default_library",
        "@com_github_kubev2v_forklift//pkg/lib/inventory/model:go_default_library",
        "@com_github_kubev2v_forklift//pkg/lib/inventory/web:go_default_library",
        "@com_github_kubev2v_forklift//pkg/lib/logging:go_default_library",
        "@io_k8s_api//core/v1:go_default_library",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:go_default_library",
        "@org_uber_go_zap//:go_default_library",
    ],
)

go_test(
    name = "collector_test",
    srcs = ["vsphere_test.go"],
    embed = [":collector"],
    deps = ["//internal/models"],
)
