load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "collector",
    srcs = [
        "logging.go",
        "vsphere.go",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/pkg/collector",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/models",
        "//pkg/vmware",
        "//vendor/github.com/go-logr/logr",
        "//vendor/github.com/kubev2v/forklift/pkg/apis/forklift/v1beta1",
        "//vendor/github.com/kubev2v/forklift/pkg/controller/provider/container/vsphere",
        "//vendor/github.com/kubev2v/forklift/pkg/controller/provider/model",
        "//vendor/github.com/kubev2v/forklift/pkg/controller/provider/web",
        "//vendor/github.com/kubev2v/forklift/pkg/controller/provider/web/base",
        "//vendor/github.com/kubev2v/forklift/pkg/controller/provider/web/vsphere",
        "//vendor/github.com/kubev2v/forklift/pkg/lib/inventory/container",
        "//vendor/github.com/kubev2v/forklift/pkg/lib/inventory/model",
        "//vendor/github.com/kubev2v/forklift/pkg/lib/inventory/web",
        "//vendor/github.com/kubev2v/forklift/pkg/lib/logging",
        "//vendor/go.uber.org/zap",
        "//vendor/k8s.io/api/core/v1:core",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
    ],
)

go_test(
    name = "collector_test",
    srcs = ["vsphere_test.go"],
    embed = [":collector"],
    deps = ["//internal/models"],
)
