load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "test",
    srcs = [
        "mock_validator.go",
        "tar.go",
        "vms.go",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/test",
    visibility = ["//visibility:public"],
    deps = [
        "//vendor/github.com/kubev2v/migration-planner/pkg/duckdb_parser",
        "//vendor/github.com/kubev2v/migration-planner/pkg/duckdb_parser/models",
    ],
)
