load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "test",
    srcs = [
        "mock_validator.go",
        "tar.go",
        "vms.go",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/test",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_kubev2v_migration_planner//pkg/duckdb_parser:go_default_library",
        "@com_github_kubev2v_migration_planner//pkg/duckdb_parser/models:go_default_library",
    ],
)
