load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "middlewares",
    srcs = ["logger.go"],
    importpath = "github.com/kubev2v/assisted-migration-agent/internal/server/middlewares",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_gin_gonic_gin//:go_default_library",
        "@org_uber_go_zap//:go_default_library",
        "@org_uber_go_zap//zapcore:go_default_library",
    ],
)
