load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "vmware",
    srcs = [
        "auth.go",
        "client.go",
        "datastore.go",
        "diskmanager.go",
        "filler_image.go",
        "finder.go",
        "helpers.go",
        "operator.go",
        "tls.go",
        "types.go",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/pkg/vmware",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/models",
        "//pkg/errors",
        "@com_github_vmware_govmomi//:go_default_library",
        "@com_github_vmware_govmomi//find:go_default_library",
        "@com_github_vmware_govmomi//object:go_default_library",
        "@com_github_vmware_govmomi//session:go_default_library",
        "@com_github_vmware_govmomi//vim25:go_default_library",
        "@com_github_vmware_govmomi//vim25/methods:go_default_library",
        "@com_github_vmware_govmomi//vim25/soap:go_default_library",
        "@com_github_vmware_govmomi//vim25/types:go_default_library",
        "@org_uber_go_zap//:go_default_library",
    ],
)

go_test(
    name = "vmware_test",
    srcs = [
        "auth_test.go",
        "datastore_test.go",
        "diskmanager_sim_test.go",
        "tls_test.go",
    ],
    embed = [":vmware"],
    deps = [
        "@com_github_vmware_govmomi//:go_default_library",
        "@com_github_vmware_govmomi//simulator:go_default_library",
    ],
)
