load("@gazelle//:def.bzl", "gazelle")
load("@rules_go//go:def.bzl", "go_binary", "go_library")

gazelle(name = "gazelle")

filegroup(
    name = "main_srcs",
    srcs = ["main.go"],
    visibility = ["//visibility:public"],
)

go_library(
    name = "assisted-migration-agent_lib",
    srcs = ["main.go"],
    importpath = "github.com/kubev2v/assisted-migration-agent",
    visibility = ["//visibility:public"],
    deps = [
        "//cmd",
        "//internal/config",
        "//pkg/logger",
        "@com_github_spf13_cobra//:go_default_library",
        "@org_uber_go_zap//:go_default_library",
        "@org_uber_go_zap//zapcore:go_default_library",
    ],
)

go_binary(
    name = "assisted-migration-agent",
    embed = [":assisted-migration-agent_lib"],
    visibility = ["//visibility:public"],
)
