load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "handlers",
    srcs = [
        "applications.go",
        "collections.go",
        "collector.go",
        "comparison.go",
        "console.go",
        "credentials.go",
        "export.go",
        "forecaster.go",
        "groups.go",
        "handlers.go",
        "inspector.go",
        "inventory.go",
        "rightsizing.go",
        "validation.go",
        "version.go",
        "virtual_machines.go",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/internal/handlers/v2",
    visibility = ["//visibility:public"],
    deps = [
        "//api/v2:api",
        "//internal/config",
        "//internal/filter",
        "//internal/models",
        "//internal/services",
        "//pkg/errors",
        "@com_github_gin_gonic_gin//:go_default_library",
        "@com_github_go_playground_validator_v10//:go_default_library",
        "@com_github_google_uuid//:go_default_library",
        "@com_github_kubev2v_migration_planner//api/v1alpha1:go_default_library",
        "@com_github_kubev2v_migration_planner//api/v1alpha1/agent:go_default_library",
        "@com_github_kubev2v_migration_planner//pkg/inventory/converters:go_default_library",
        "@org_uber_go_zap//:go_default_library",
    ],
)

go_test(
    name = "handlers_test",
    srcs = [
        "collector_test.go",
        "comparison_test.go",
        "groups_test.go",
        "handlers_suite_test.go",
        "inspector_test.go",
        "inventory_test.go",
    ],
    deps = [
        ":handlers",
        "//api/v2:api",
        "//internal/config",
        "//internal/models",
        "//internal/services",
        "//internal/store",
        "//internal/store/migrations",
        "//pkg/crypto",
        "//pkg/errors",
        "@com_github_gin_gonic_gin//:go_default_library",
        "@com_github_google_uuid//:go_default_library",
        "@com_github_kubev2v_migration_planner//api/v1alpha1:go_default_library",
        "@com_github_kubev2v_migration_planner//api/v1alpha1/agent:go_default_library",
        "@com_github_kubev2v_migration_planner//pkg/duckdb_parser:go_default_library",
        "@com_github_kubev2v_migration_planner//pkg/inventory:go_default_library",
        "@com_github_onsi_ginkgo_v2//:go_default_library",
        "@com_github_onsi_gomega//:go_default_library",
    ],
)
