load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "handlers",
    srcs = [
        "applications.go",
        "collections.go",
        "collector.go",
        "comparison.go",
        "console.go",
        "credentials.go",
        "export.go",
        "forecaster.go",
        "groups.go",
        "handlers.go",
        "inspector.go",
        "inventory.go",
        "rightsizing.go",
        "rvtools.go",
        "validation.go",
        "version.go",
        "virtual_machines.go",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/internal/handlers/v2",
    visibility = ["//visibility:public"],
    deps = [
        "//api/v2:api",
        "//internal/config",
        "//internal/filter",
        "//internal/models",
        "//internal/services",
        "//pkg/errors",
        "//vendor/github.com/gin-gonic/gin",
        "//vendor/github.com/go-playground/validator/v10:validator",
        "//vendor/github.com/google/uuid",
        "//vendor/github.com/kubev2v/migration-planner/api/v1alpha1",
        "//vendor/github.com/kubev2v/migration-planner/api/v1alpha1/agent",
        "//vendor/github.com/kubev2v/migration-planner/pkg/inventory/converters",
        "//vendor/go.uber.org/zap",
    ],
)

go_test(
    name = "handlers_test",
    srcs = [
        "collector_test.go",
        "comparison_test.go",
        "groups_test.go",
        "handlers_suite_test.go",
        "inspector_test.go",
        "inventory_test.go",
    ],
    deps = [
        ":handlers",
        "//api/v2:api",
        "//internal/config",
        "//internal/models",
        "//internal/services",
        "//internal/store",
        "//internal/store/migrations",
        "//pkg/crypto",
        "//pkg/errors",
        "//vendor/github.com/gin-gonic/gin",
        "//vendor/github.com/google/uuid",
        "//vendor/github.com/kubev2v/migration-planner/api/v1alpha1",
        "//vendor/github.com/kubev2v/migration-planner/api/v1alpha1/agent",
        "//vendor/github.com/kubev2v/migration-planner/pkg/duckdb_parser",
        "//vendor/github.com/kubev2v/migration-planner/pkg/inventory",
        "//vendor/github.com/onsi/ginkgo/v2:ginkgo",
        "//vendor/github.com/onsi/gomega",
    ],
)
