load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "filter",
    srcs = [
        "mappers.go",
        "test_helpers.go",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/internal/filter",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/filter",
        "@com_github_masterminds_squirrel//:go_default_library",
    ],
)

go_test(
    name = "filter_test",
    srcs = [
        "application_test.go",
        "filter_suite_test.go",
        "groups_test.go",
        "labels_integration_test.go",
        "labels_test.go",
        "mappers_test.go",
        "migration_excluded_test.go",
        "sql_integration_test.go",
    ],
    embed = [":filter"],
    deps = [
        "//pkg/filter",
        "@com_github_duckdb_duckdb_go_v2//:go_default_library",
        "@com_github_masterminds_squirrel//:go_default_library",
        "@com_github_onsi_ginkgo_v2//:go_default_library",
        "@com_github_onsi_gomega//:go_default_library",
    ],
)
