load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "filter",
    srcs = [
        "ast.go",
        "doc.go",
        "lexer.go",
        "parser.go",
        "sql.go",
        "tokens.go",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/pkg/filter",
    visibility = ["//visibility:public"],
    deps = ["@com_github_masterminds_squirrel//:go_default_library"],
)

go_test(
    name = "filter_test",
    srcs = [
        "filter_suite_test.go",
        "fuzz_test.go",
        "lexer_test.go",
        "parser_test.go",
        "sql_test.go",
    ],
    embed = [":filter"],
    deps = [
        "//internal/filter",
        "@com_github_onsi_ginkgo_v2//:go_default_library",
        "@com_github_onsi_gomega//:go_default_library",
    ],
)
