load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "crypto",
    srcs = [
        "crypto.go",
        "keymanager.go",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/pkg/crypto",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/models",
        "@org_golang_x_crypto//argon2:go_default_library",
        "@org_golang_x_crypto//chacha20poly1305:go_default_library",
        "@org_uber_go_zap//:go_default_library",
    ],
)

go_test(
    name = "crypto_test",
    srcs = [
        "crypto_suite_test.go",
        "crypto_test.go",
        "keymanager_test.go",
    ],
    deps = [
        ":crypto",
        "//internal/models",
        "@com_github_onsi_ginkgo_v2//:go_default_library",
        "@com_github_onsi_gomega//:go_default_library",
    ],
)
