load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "server",
    srcs = [
        "doc.go",
        "http.go",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/internal/server",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/config",
        "//internal/server/middlewares",
        "//pkg/certificates",
        "@com_github_getkin_kin_openapi//openapi3:go_default_library",
        "@com_github_gin_contrib_zap//:go_default_library",
        "@com_github_gin_gonic_gin//:go_default_library",
        "@com_github_oapi_codegen_gin_middleware//:go_default_library",
        "@org_uber_go_zap//:go_default_library",
    ],
)

go_test(
    name = "server_test",
    srcs = [
        "http_test.go",
        "server_suite_test.go",
    ],
    deps = [
        ":server",
        "//internal/config",
        "@com_github_gin_gonic_gin//:go_default_library",
        "@com_github_onsi_ginkgo_v2//:go_default_library",
        "@com_github_onsi_gomega//:go_default_library",
    ],
)
