load("@rules_go//go:def.bzl", "go_test")
load(":defs.bzl", "bootstrap_library")

filegroup(
    name = "core_srcs",
    srcs = ["bootstrap.go", "builder.go"],
    visibility = ["//visibility:public"],
)

exports_files(["default_bootstrap.go"])

bootstrap_library(
    name = "bootstrap",
    visibility = ["//visibility:public"],
)

go_test(
    name = "bootstrap_test",
    srcs = ["builder_test.go"],
    embed = [":bootstrap"],
    deps = [
        "//internal/config",
        "//internal/server",
        "//internal/services",
        "//internal/store",
        "@com_github_gin_gonic_gin//:go_default_library",
    ],
)
