load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "service",
    srcs = ["agent.go"],
    importpath = "github.com/kubev2v/assisted-migration-agent/test/e2e-v2/service",
    visibility = ["//visibility:public"],
    deps = [
        "//api/v2:api",
        "@com_github_kubev2v_migration_planner//api/v1alpha1:go_default_library",
        "@org_uber_go_zap//:go_default_library",
    ],
)
