load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "utils",
    srcs = [
        "auth.go",
        "command.go",
        "file.go",
        "rvtools.go",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/pkg/e2e/utils",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/e2e/model",
        "@com_github_golang_jwt_jwt_v5//:go_default_library",
        "@com_github_kubev2v_migration_planner//test/e2e/config:go_default_library",
        "@com_github_xuri_excelize_v2//:go_default_library",
    ],
)
