load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "backend",
    srcs = [
        "assessment.go",
        "interfaces.go",
        "service.go",
        "service_api.go",
        "source.go",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/pkg/e2e/backend",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/e2e/model",
        "//pkg/e2e/utils",
        "@com_github_google_uuid//:go_default_library",
        "@com_github_kubev2v_migration_planner//api/v1alpha1:go_default_library",
        "@com_github_kubev2v_migration_planner//test/e2e/config:go_default_library",
        "@org_uber_go_zap//:go_default_library",
    ],
)
