load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "rightsizing",
    srcs = [
        "stats.go",
        "vsphere.go",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/pkg/rightsizing",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_vmware_govmomi//:go_default_library",
        "@com_github_vmware_govmomi//performance:go_default_library",
        "@com_github_vmware_govmomi//session:go_default_library",
        "@com_github_vmware_govmomi//view:go_default_library",
        "@com_github_vmware_govmomi//vim25:go_default_library",
        "@com_github_vmware_govmomi//vim25/mo:go_default_library",
        "@com_github_vmware_govmomi//vim25/soap:go_default_library",
        "@com_github_vmware_govmomi//vim25/types:go_default_library",
    ],
)

go_test(
    name = "rightsizing_test",
    srcs = [
        "stats_test.go",
        "vsphere_test.go",
    ],
    embed = [":rightsizing"],
)
