load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "console",
    srcs = [
        "client.go",
        "request_builder.go",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/pkg/console",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/models",
        "//pkg/errors",
        "@com_github_google_uuid//:go_default_library",
        "@com_github_kubev2v_migration_planner//api/v1alpha1:go_default_library",
        "@com_github_kubev2v_migration_planner//api/v1alpha1/agent:go_default_library",
        "@com_github_kubev2v_migration_planner//pkg/client:go_default_library",
    ],
)

go_test(
    name = "console_test",
    srcs = ["request_builder_test.go"],
    deps = [
        ":console",
        "//internal/models",
        "//pkg/errors",
        "@com_github_google_uuid//:go_default_library",
        "@com_github_kubev2v_migration_planner//api/v1alpha1:go_default_library",
        "@com_github_kubev2v_migration_planner//api/v1alpha1/agent:go_default_library",
        "@com_github_onsi_ginkgo_v2//:go_default_library",
        "@com_github_onsi_gomega//:go_default_library",
    ],
)
