load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "migrations",
    srcs = ["migrations.go"],
    embedsrcs = [
        "collection/001_initial.sql",
        "main/001_initial.sql",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/internal/store/migrations",
    visibility = ["//visibility:public"],
    deps = ["@org_uber_go_zap//:go_default_library"],
)

go_test(
    name = "migrations_test",
    srcs = ["migrations_test.go"],
    deps = [
        ":migrations",
        "//internal/store",
        "@com_github_kubev2v_migration_planner//pkg/duckdb_parser:go_default_library",
        "@com_github_onsi_ginkgo_v2//:go_default_library",
        "@com_github_onsi_gomega//:go_default_library",
    ],
)
