load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "vcsim",
    srcs = [
        "dataset.go",
        "helpers.go",
        "model.go",
    ],
    embedsrcs = [
        "basemodel/0000-ServiceInstance-ServiceInstance.xml",
        "basemodel/0001-Folder-group-d1.xml",
        "basemodel/0002-PropertyCollector-propertyCollector.xml",
        "basemodel/0003-ViewManager-ViewManager.xml",
        "basemodel/0004-OptionManager-VpxSettings.xml",
        "basemodel/0005-UserDirectory-UserDirectory.xml",
        "basemodel/0006-SessionManager-SessionManager.xml",
        "basemodel/0007-AuthorizationManager-AuthorizationManager.xml",
        "basemodel/0008-ServiceManager-ServiceMgr.xml",
        "basemodel/0009-PerformanceManager-PerfMgr.xml",
        "basemodel/0010-ScheduledTaskManager-ScheduledTaskManager.xml",
        "basemodel/0011-AlarmManager-AlarmManager.xml",
        "basemodel/0012-Alarm-alarm-384.xml",
        "basemodel/0013-Alarm-alarm-11.xml",
        "basemodel/0014-Alarm-alarm-12.xml",
        "basemodel/0015-EventManager-EventManager.xml",
        "basemodel/0016-TaskManager-TaskManager.xml",
        "basemodel/0017-ExtensionManager-ExtensionManager.xml",
        "basemodel/0018-CustomizationSpecManager-CustomizationSpecManager.xml",
        "basemodel/0019-CustomFieldsManager-CustomFieldsManager.xml",
        "basemodel/0020-DiagnosticManager-DiagMgr.xml",
        "basemodel/0021-LicenseManager-LicenseManager.xml",
        "basemodel/0022-SearchIndex-SearchIndex.xml",
        "basemodel/0023-FileManager-FileManager.xml",
        "basemodel/0024-DatastoreNamespaceManager-DatastoreNamespaceManager.xml",
        "basemodel/0025-VirtualDiskManager-virtualDiskManager.xml",
        "basemodel/0026-HostSnmpSystem-SnmpSystem.xml",
        "basemodel/0027-VirtualMachineProvisioningChecker-ProvChecker.xml",
        "basemodel/0028-VirtualMachineCompatibilityChecker-CompatChecker.xml",
        "basemodel/0029-OvfManager-OvfManager.xml",
        "basemodel/0030-IpPoolManager-IpPoolManager.xml",
        "basemodel/0031-DistributedVirtualSwitchManager-DVSManager.xml",
        "basemodel/0032-HostProfileManager-HostProfileManager.xml",
        "basemodel/0033-ClusterProfileManager-ClusterProfileManager.xml",
        "basemodel/0034-ProfileComplianceManager-MoComplianceManager.xml",
        "basemodel/0035-LocalizationManager-LocalizationManager.xml",
        "basemodel/0036-StorageResourceManager-StorageResourceManager.xml",
        "basemodel/0037-GuestOperationsManager-guestOperationsManager.xml",
        "basemodel/0038-OverheadMemoryManager-OverheadMemoryManager.xml",
        "basemodel/0039-CertificateManager-certificateManager.xml",
        "basemodel/0040-IoFilterManager-IoFilterManager.xml",
        "basemodel/0041-VcenterVStorageObjectManager-VStorageObjectManager.xml",
        "basemodel/0042-HostSpecificationManager-HostSpecificationManager.xml",
        "basemodel/0043-CryptoManagerKmip-CryptoManager.xml",
        "basemodel/0044-HealthUpdateManager-HealthUpdateManager.xml",
        "basemodel/0045-FailoverClusterConfigurator-FailoverClusterConfigurator.xml",
        "basemodel/0046-FailoverClusterManager-FailoverClusterManager.xml",
        "basemodel/0047-TenantTenantManager-TenantManager.xml",
        "basemodel/0048-Datacenter-datacenter-1.xml",
        "basemodel/0055-EnvironmentBrowser-envbrowser-22.xml",
        "basemodel/0060-EnvironmentBrowser-envbrowser-26.xml",
        "basemodel/0064-Folder-group-3.xml",
        "basemodel/0065-Task-task-13.xml",
        "basemodel/0066-ComputeResource-domain-s24.xml",
        "basemodel/0067-HostSystem-host-21.xml",
        "basemodel/0068-HostDatastoreSystem-hostdatastoresystem-14.xml",
        "basemodel/0069-HostNetworkSystem-hostnetworksystem-15.xml",
        "basemodel/0070-HostVirtualNicManager-hostvirtualnicmanager-16.xml",
        "basemodel/0071-HostCertificateManager-hostcertificatemanager-20.xml",
        "basemodel/0072-ResourcePool-resgroup-23.xml",
        "basemodel/0073-ClusterComputeResource-domain-c28.xml",
        "basemodel/0075-HostSystem-host-37.xml",
        "basemodel/0076-HostDatastoreSystem-hostdatastoresystem-30.xml",
        "basemodel/0077-HostNetworkSystem-hostnetworksystem-31.xml",
        "basemodel/0078-HostVirtualNicManager-hostvirtualnicmanager-32.xml",
        "basemodel/0079-HostCertificateManager-hostcertificatemanager-36.xml",
        "basemodel/0080-ResourcePool-resgroup-27.xml",
        "basemodel/0081-Folder-group-4.xml",
        "basemodel/0082-Datastore-datastore-39.xml",
        "basemodel/0083-HostDatastoreBrowser-hostdatastorebrowser-40.xml",
        "basemodel/0084-Folder-group-5.xml",
        "basemodel/0085-Task-task-7.xml",
        "basemodel/0086-Network-network-6.xml",
        "basemodel/0087-DistributedVirtualSwitch-dvs-8.xml",
        "basemodel/0088-Task-task-9.xml",
        "basemodel/0089-Task-task-11.xml",
        "basemodel/0090-Datastore-datastore-41.xml",
        "basemodel/0091-HostDatastoreBrowser-hostdatastorebrowser-42.xml",
        "basemodel/0092-DistributedVirtualPortgroup-dvportgroup-10.xml",
        "basemodel/0093-DistributedVirtualPortgroup-dvportgroup-12.xml",
        "basemodel/AlarmManager-AlarmManager/GetAlarm.xml",
        "basemodel/EnvironmentBrowser-envbrowser-22/QueryConfigOption.xml",
        "basemodel/EnvironmentBrowser-envbrowser-22/QueryConfigTarget.xml",
        "basemodel/EnvironmentBrowser-envbrowser-22/QueryTargetCapabilities.xml",
        "basemodel/EnvironmentBrowser-envbrowser-26/QueryConfigOption.xml",
        "basemodel/EnvironmentBrowser-envbrowser-26/QueryConfigTarget.xml",
        "basemodel/EnvironmentBrowser-envbrowser-26/QueryTargetCapabilities.xml",
        "basemodel/HostNetworkSystem-hostnetworksystem-15/QueryNetworkHint.xml",
        "basemodel/HostNetworkSystem-hostnetworksystem-31/QueryNetworkHint.xml",
        "basemodel/HostSystem-host-21/QueryTpmAttestationReport.xml",
        "basemodel/HostSystem-host-37/QueryTpmAttestationReport.xml",
        "templates/folder.xml.tmpl",
        "templates/task_create_vm.xml.tmpl",
        "templates/task_power_on.xml.tmpl",
        "templates/vm.xml.tmpl",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/pkg/e2e/vcsim",
    visibility = ["//visibility:public"],
)
