load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "infra",
    srcs = [
        "container.go",
        "infra.go",
        "observer.go",
        "oidc.go",
        "podman.go",
        "proxy.go",
        "vm.go",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/pkg/e2e/infra",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/e2e/vcsim",
        "//vendor/github.com/golang-jwt/jwt/v5:jwt",
        "//vendor/github.com/google/uuid",
        "//vendor/github.com/opencontainers/runtime-spec/specs-go",
        "//vendor/go.podman.io/common/libnetwork/types",
        "//vendor/go.podman.io/podman/v6/pkg/bindings",
        "//vendor/go.podman.io/podman/v6/pkg/bindings/containers",
        "//vendor/go.podman.io/podman/v6/pkg/bindings/network",
        "//vendor/go.podman.io/podman/v6/pkg/bindings/volumes",
        "//vendor/go.podman.io/podman/v6/pkg/specgen",
        "//vendor/go.uber.org/zap",
    ],
)
