load("@rules_go//go:def.bzl", "go_library", "go_test")

filegroup(
    name = "srcs",
    srcs = glob(["*.go"], exclude = ["*_test.go"]),
    visibility = ["//visibility:public"],
)

go_library(
    name = "cmd",
    srcs = [
        "run.go",
        "version.go",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/cmd",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/bootstrap",
        "//internal/config",
        "//internal/models",
        "@com_github_ecordell_optgen//helpers:go_default_library",
        "@com_github_fatih_color//:go_default_library",
        "@com_github_go_extras_cobraflags//:go_default_library",
        "@com_github_jzelinskie_cobrautil_v2//:go_default_library",
        "@com_github_spf13_cobra//:go_default_library",
        "@com_github_spf13_pflag//:go_default_library",
        "@org_uber_go_zap//:go_default_library",
    ],
)

go_test(
    name = "cmd_test",
    srcs = ["run_test.go"],
    embed = [":cmd"],
    deps = [
        "//internal/bootstrap",
        "//internal/config",
        "//internal/store",
        "//internal/store/migrations",
        "@com_github_go_extras_cobraflags//:go_default_library",
        "@com_github_onsi_ginkgo_v2//:go_default_library",
        "@com_github_onsi_gomega//:go_default_library",
        "@com_github_spf13_pflag//:go_default_library",
        "@com_github_spf13_viper//:go_default_library",
    ],
)
