load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "e2e-v2_lib",
    srcs = [
        "main.go",
        "test_applications_endpoint.go",
        "test_collections_endpoint.go",
        "test_connected_env.go",
        "test_groups_endpoint.go",
        "test_groups_inventory.go",
        "test_migration_exclusion.go",
        "test_validation.go",
        "test_vm_labels.go",
        "test_vms_endpoint.go",
        "tests.go",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/test/e2e-v2",
    visibility = ["//visibility:private"],
    deps = [
        "//api/v2:api",
        "//pkg/e2e/backend",
        "//pkg/e2e/infra",
        "//pkg/e2e/vcsim",
        "//test/e2e-v2/service",
        "@com_github_google_uuid//:go_default_library",
        "@com_github_kubev2v_migration_planner//api/v1alpha1:go_default_library",
        "@com_github_kubev2v_migration_planner//api/v1alpha1/agent:go_default_library",
        "@com_github_oapi_codegen_runtime//types:go_default_library",
        "@com_github_onsi_ginkgo_v2//:go_default_library",
        "@com_github_onsi_gomega//:go_default_library",
        "@org_uber_go_zap//:go_default_library",
    ],
)

go_binary(
    name = "e2e-v2",
    embed = [":e2e-v2_lib"],
    visibility = ["//visibility:public"],
)
