load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "handlers",
    srcs = ["validation.go"],
    importpath = "github.com/kubev2v/assisted-migration-agent/internal/handlers",
    visibility = ["//visibility:public"],
    deps = ["//vendor/github.com/go-playground/validator/v10:validator"],
)
