load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "handlers",
    srcs = ["validation.go"],
    importpath = "github.com/kubev2v/assisted-migration-agent/internal/handlers",
    visibility = ["//visibility:public"],
    deps = ["@com_github_go_playground_validator_v10//:go_default_library"],
)
