load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "api",
    srcs = [
        "docs.go",
        "extension.go",
        "spec.gen.go",
        "types.gen.go",
    ],
    importpath = "github.com/kubev2v/assisted-migration-agent/api/v2",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/models",
        "//internal/store",
        "@com_github_getkin_kin_openapi//openapi3:go_default_library",
        "@com_github_gin_gonic_gin//:go_default_library",
        "@com_github_kubev2v_migration_planner//api/v1alpha1:go_default_library",
        "@com_github_oapi_codegen_runtime//:go_default_library",
        "@com_github_oapi_codegen_runtime//types:go_default_library",
    ],
)

go_test(
    name = "api_test",
    srcs = ["extension_test.go"],
    deps = [
        ":api",
        "//internal/models",
        "@com_github_onsi_ginkgo_v2//:go_default_library",
        "@com_github_onsi_gomega//:go_default_library",
    ],
)
