// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v2

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get agent status
	// (GET /agent)
	GetAgentStatus(c *gin.Context)
	// Change agent mode
	// (POST /agent)
	SetAgentMode(c *gin.Context)
	// Delete all collections
	// (DELETE /collections)
	DeleteCollections(c *gin.Context)
	// List all collections
	// (GET /collections)
	ListCollections(c *gin.Context)
	// Compare two collections — returns aggregates and diffs
	// (GET /collections/compare/{aId}/{bId})
	CompareCollections(c *gin.Context, aId string, bId string)
	// Drill down — VM IDs that differ between two collections for a given dimension
	// (GET /collections/compare/{aId}/{bId}/{dimension})
	CompareCollectionsDiff(c *gin.Context, aId string, bId string, dimension CompareCollectionsDiffParamsDimension, params CompareCollectionsDiffParams)
	// List detected applications in a collection
	// (GET /collections/{id}/applications)
	ListApplications(c *gin.Context, id string)
	// Get latest cluster utilization by cluster ID
	// (GET /collections/{id}/clusters/{clusterId}/utilization)
	GetClusterUtilization(c *gin.Context, id string, clusterId string)
	// Export collection data as CSV ZIP archive or Excel workbook
	// (GET /collections/{id}/export)
	ExportCollection(c *gin.Context, id string, params ExportCollectionParams)
	// List all groups in a collection
	// (GET /collections/{id}/groups)
	ListGroups(c *gin.Context, id string, params ListGroupsParams)
	// Get group by ID with its VirtualMachines
	// (GET /collections/{id}/groups/{groupId})
	GetGroup(c *gin.Context, id string, groupId string, params GetGroupParams)
	// Get collected inventory for a collection
	// (GET /collections/{id}/inventory)
	GetInventory(c *gin.Context, id string)
	// List VirtualMachines in a collection
	// (GET /collections/{id}/virtualmachines)
	ListVirtualMachines(c *gin.Context, id string, params ListVirtualMachinesParams)
	// Get available filter option values
	// (GET /collections/{id}/virtualmachines/filter-options)
	GetVMFilterOptions(c *gin.Context, id string)
	// Get all distinct labels with counts
	// (GET /collections/{id}/virtualmachines/labels)
	GetVMLabels(c *gin.Context, id string)
	// Get VirtualMachine details
	// (GET /collections/{id}/virtualmachines/{vmId})
	GetVirtualMachine(c *gin.Context, id string, vmId string)
	// Get utilization breakdown for a specific VM
	// (GET /collections/{id}/virtualmachines/{vmId}/utilization)
	GetVMUtilization(c *gin.Context, id string, vmId string)
	// Stop collector
	// (DELETE /collector)
	StopCollector(c *gin.Context)
	// Get collector status
	// (GET /collector)
	GetCollectorStatus(c *gin.Context)
	// Start a collection
	// (POST /collector)
	StartCollector(c *gin.Context)
	// Delete stored credentials
	// (DELETE /credentials)
	DeleteCredentials(c *gin.Context)
	// Get stored credential status
	// (GET /credentials)
	GetCredentials(c *gin.Context)
	// Store vCenter credentials
	// (PUT /credentials)
	PutCredentials(c *gin.Context)
	// Check vSphere operation capabilities
	// (GET /credentials/capabilities)
	GetCredentialCapabilities(c *gin.Context)
	// Cancel benchmark
	// (DELETE /forecaster)
	StopForecaster(c *gin.Context)
	// Poll forecaster status
	// (GET /forecaster)
	GetForecasterStatus(c *gin.Context)
	// Start benchmark
	// (POST /forecaster)
	StartForecaster(c *gin.Context)
	// Compute pair capabilities
	// (POST /forecaster/capabilities)
	PostForecasterPairCapabilities(c *gin.Context)
	// List available datastores
	// (GET /forecaster/datastores)
	GetForecasterDatastores(c *gin.Context)
	// Cancel a single pair
	// (DELETE /forecaster/pairs/{name})
	StopForecasterPair(c *gin.Context, name string)
	// List benchmark runs
	// (GET /forecaster/runs)
	GetForecasterRuns(c *gin.Context, params GetForecasterRunsParams)
	// Delete a benchmark run
	// (DELETE /forecaster/runs/{id})
	DeleteForecasterRun(c *gin.Context, id int64)
	// Get throughput statistics
	// (GET /forecaster/stats)
	GetForecasterStats(c *gin.Context, params GetForecasterStatsParams)
	// List groups from the latest collection
	// (GET /groups)
	ListLatestGroups(c *gin.Context, params ListLatestGroupsParams)
	// Create a new group in the latest collection
	// (POST /groups)
	CreateLatestGroup(c *gin.Context)
	// Delete group from the latest collection
	// (DELETE /groups/{groupId})
	DeleteLatestGroup(c *gin.Context, groupId string)
	// Get group by ID from the latest collection
	// (GET /groups/{groupId})
	GetLatestGroup(c *gin.Context, groupId string, params GetLatestGroupParams)
	// Update group in the latest collection
	// (PATCH /groups/{groupId})
	UpdateLatestGroup(c *gin.Context, groupId string)
	// List detected applications for a group
	// (GET /groups/{groupId}/applications)
	ListGroupApplications(c *gin.Context, groupId string)
	// Stop inspector
	// (DELETE /inspector)
	StopInspection(c *gin.Context)
	// Get inspector status
	// (GET /inspector)
	GetInspectorStatus(c *gin.Context, params GetInspectorStatusParams)
	// Start deep inspection for VMs
	// (POST /inspector)
	StartInspection(c *gin.Context)
	// Get VDDK upload status
	// (GET /inspector/vddk)
	GetInspectorVddkStatus(c *gin.Context)
	// Upload VDDK tarball
	// (PUT /inspector/vddk)
	PutInspectorVddk(c *gin.Context)
	// Get inventory from the latest collection
	// (GET /inventory)
	GetLatestInventory(c *gin.Context, params GetLatestInventoryParams)
	// Get agent version information
	// (GET /version)
	GetVersion(c *gin.Context)
	// List VirtualMachines from the latest collection
	// (GET /virtualmachines)
	ListLatestVirtualMachines(c *gin.Context, params ListLatestVirtualMachinesParams)
	// Batch update migration exclusion for multiple VMs in the latest collection
	// (POST /virtualmachines/batch-update-exclusion)
	BatchUpdateLatestVMExclusion(c *gin.Context)
	// Get available filter option values from the latest collection
	// (GET /virtualmachines/filter-options)
	GetLatestVMFilterOptions(c *gin.Context)
	// Get all distinct labels with counts from the latest collection
	// (GET /virtualmachines/labels)
	GetLatestVMLabels(c *gin.Context)
	// Remove a label from all VMs in the latest collection
	// (DELETE /virtualmachines/labels/{label})
	DeleteLatestLabelGlobally(c *gin.Context, label string)
	// Add or remove a label from multiple VMs in the latest collection
	// (PATCH /virtualmachines/labels/{label})
	UpdateLatestLabelVMs(c *gin.Context, label string)
	// Get VirtualMachine details from the latest collection
	// (GET /virtualmachines/{vmId})
	GetLatestVirtualMachine(c *gin.Context, vmId string)
	// Update VirtualMachine properties in the latest collection
	// (PATCH /virtualmachines/{vmId})
	UpdateLatestVirtualMachine(c *gin.Context, vmId string)
	// Cancel deep inspection for a specific VirtualMachine
	// (DELETE /virtualmachines/{vmId}/inspection)
	CancelVirtualMachineInspection(c *gin.Context, vmId string)
	// Get utilization breakdown for a specific VM from the latest collection
	// (GET /virtualmachines/{vmId}/utilization)
	GetLatestVMUtilization(c *gin.Context, vmId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAgentStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAgentStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAgentStatus(c)
}

// SetAgentMode operation middleware
func (siw *ServerInterfaceWrapper) SetAgentMode(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetAgentMode(c)
}

// DeleteCollections operation middleware
func (siw *ServerInterfaceWrapper) DeleteCollections(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCollections(c)
}

// ListCollections operation middleware
func (siw *ServerInterfaceWrapper) ListCollections(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListCollections(c)
}

// CompareCollections operation middleware
func (siw *ServerInterfaceWrapper) CompareCollections(c *gin.Context) {

	var err error

	// ------------- Path parameter "aId" -------------
	var aId string

	err = runtime.BindStyledParameterWithOptions("simple", "aId", c.Param("aId"), &aId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter aId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "bId" -------------
	var bId string

	err = runtime.BindStyledParameterWithOptions("simple", "bId", c.Param("bId"), &bId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter bId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompareCollections(c, aId, bId)
}

// CompareCollectionsDiff operation middleware
func (siw *ServerInterfaceWrapper) CompareCollectionsDiff(c *gin.Context) {

	var err error

	// ------------- Path parameter "aId" -------------
	var aId string

	err = runtime.BindStyledParameterWithOptions("simple", "aId", c.Param("aId"), &aId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter aId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "bId" -------------
	var bId string

	err = runtime.BindStyledParameterWithOptions("simple", "bId", c.Param("bId"), &bId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter bId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "dimension" -------------
	var dimension CompareCollectionsDiffParamsDimension

	err = runtime.BindStyledParameterWithOptions("simple", "dimension", c.Param("dimension"), &dimension, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dimension: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CompareCollectionsDiffParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompareCollectionsDiff(c, aId, bId, dimension, params)
}

// ListApplications operation middleware
func (siw *ServerInterfaceWrapper) ListApplications(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListApplications(c, id)
}

// GetClusterUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetClusterUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "clusterId" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "clusterId", c.Param("clusterId"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter clusterId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClusterUtilization(c, id, clusterId)
}

// ExportCollection operation middleware
func (siw *ServerInterfaceWrapper) ExportCollection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportCollectionParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", c.Request.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scope: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameter("form", true, false, "format", c.Request.URL.Query(), &params.Format)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter format: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExportCollection(c, id, params)
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGroups(c, id, params)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGroup(c, id, groupId, params)
}

// GetInventory operation middleware
func (siw *ServerInterfaceWrapper) GetInventory(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInventory(c, id)
}

// ListVirtualMachines operation middleware
func (siw *ServerInterfaceWrapper) ListVirtualMachines(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVirtualMachinesParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListVirtualMachines(c, id, params)
}

// GetVMFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetVMFilterOptions(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMFilterOptions(c, id)
}

// GetVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetVMLabels(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMLabels(c, id)
}

// GetVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) GetVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVirtualMachine(c, id, vmId)
}

// GetVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMUtilization(c, id, vmId)
}

// StopCollector operation middleware
func (siw *ServerInterfaceWrapper) StopCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopCollector(c)
}

// GetCollectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetCollectorStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCollectorStatus(c)
}

// StartCollector operation middleware
func (siw *ServerInterfaceWrapper) StartCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartCollector(c)
}

// DeleteCredentials operation middleware
func (siw *ServerInterfaceWrapper) DeleteCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCredentials(c)
}

// GetCredentials operation middleware
func (siw *ServerInterfaceWrapper) GetCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentials(c)
}

// PutCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutCredentials(c)
}

// GetCredentialCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetCredentialCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentialCapabilities(c)
}

// StopForecaster operation middleware
func (siw *ServerInterfaceWrapper) StopForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecaster(c)
}

// GetForecasterStatus operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStatus(c)
}

// StartForecaster operation middleware
func (siw *ServerInterfaceWrapper) StartForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartForecaster(c)
}

// PostForecasterPairCapabilities operation middleware
func (siw *ServerInterfaceWrapper) PostForecasterPairCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostForecasterPairCapabilities(c)
}

// GetForecasterDatastores operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterDatastores(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterDatastores(c)
}

// StopForecasterPair operation middleware
func (siw *ServerInterfaceWrapper) StopForecasterPair(c *gin.Context) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Param("name"), &name, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecasterPair(c, name)
}

// GetForecasterRuns operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterRuns(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterRunsParams

	// ------------- Optional query parameter "pairName" -------------

	err = runtime.BindQueryParameter("form", true, false, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterRuns(c, params)
}

// DeleteForecasterRun operation middleware
func (siw *ServerInterfaceWrapper) DeleteForecasterRun(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteForecasterRun(c, id)
}

// GetForecasterStats operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStats(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterStatsParams

	// ------------- Required query parameter "pairName" -------------

	if paramValue := c.Query("pairName"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument pairName is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStats(c, params)
}

// ListLatestGroups operation middleware
func (siw *ServerInterfaceWrapper) ListLatestGroups(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLatestGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLatestGroups(c, params)
}

// CreateLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateLatestGroup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateLatestGroup(c)
}

// DeleteLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLatestGroup(c, groupId)
}

// GetLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) GetLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestGroup(c, groupId, params)
}

// UpdateLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestGroup(c, groupId)
}

// ListGroupApplications operation middleware
func (siw *ServerInterfaceWrapper) ListGroupApplications(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGroupApplications(c, groupId)
}

// StopInspection operation middleware
func (siw *ServerInterfaceWrapper) StopInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopInspection(c)
}

// GetInspectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorStatus(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInspectorStatusParams

	// ------------- Optional query parameter "includeVddk" -------------

	err = runtime.BindQueryParameter("form", true, false, "includeVddk", c.Request.URL.Query(), &params.IncludeVddk)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter includeVddk: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorStatus(c, params)
}

// StartInspection operation middleware
func (siw *ServerInterfaceWrapper) StartInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartInspection(c)
}

// GetInspectorVddkStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorVddkStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorVddkStatus(c)
}

// PutInspectorVddk operation middleware
func (siw *ServerInterfaceWrapper) PutInspectorVddk(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutInspectorVddk(c)
}

// GetLatestInventory operation middleware
func (siw *ServerInterfaceWrapper) GetLatestInventory(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestInventoryParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", c.Request.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scope: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestInventory(c, params)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVersion(c)
}

// ListLatestVirtualMachines operation middleware
func (siw *ServerInterfaceWrapper) ListLatestVirtualMachines(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLatestVirtualMachinesParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLatestVirtualMachines(c, params)
}

// BatchUpdateLatestVMExclusion operation middleware
func (siw *ServerInterfaceWrapper) BatchUpdateLatestVMExclusion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.BatchUpdateLatestVMExclusion(c)
}

// GetLatestVMFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMFilterOptions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMFilterOptions(c)
}

// GetLatestVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMLabels(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMLabels(c)
}

// DeleteLatestLabelGlobally operation middleware
func (siw *ServerInterfaceWrapper) DeleteLatestLabelGlobally(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLatestLabelGlobally(c, label)
}

// UpdateLatestLabelVMs operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestLabelVMs(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestLabelVMs(c, label)
}

// GetLatestVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVirtualMachine(c, vmId)
}

// UpdateLatestVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestVirtualMachine(c, vmId)
}

// CancelVirtualMachineInspection operation middleware
func (siw *ServerInterfaceWrapper) CancelVirtualMachineInspection(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CancelVirtualMachineInspection(c, vmId)
}

// GetLatestVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMUtilization(c, vmId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/agent", wrapper.GetAgentStatus)
	router.POST(options.BaseURL+"/agent", wrapper.SetAgentMode)
	router.DELETE(options.BaseURL+"/collections", wrapper.DeleteCollections)
	router.GET(options.BaseURL+"/collections", wrapper.ListCollections)
	router.GET(options.BaseURL+"/collections/compare/:aId/:bId", wrapper.CompareCollections)
	router.GET(options.BaseURL+"/collections/compare/:aId/:bId/:dimension", wrapper.CompareCollectionsDiff)
	router.GET(options.BaseURL+"/collections/:id/applications", wrapper.ListApplications)
	router.GET(options.BaseURL+"/collections/:id/clusters/:clusterId/utilization", wrapper.GetClusterUtilization)
	router.GET(options.BaseURL+"/collections/:id/export", wrapper.ExportCollection)
	router.GET(options.BaseURL+"/collections/:id/groups", wrapper.ListGroups)
	router.GET(options.BaseURL+"/collections/:id/groups/:groupId", wrapper.GetGroup)
	router.GET(options.BaseURL+"/collections/:id/inventory", wrapper.GetInventory)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines", wrapper.ListVirtualMachines)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/filter-options", wrapper.GetVMFilterOptions)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/labels", wrapper.GetVMLabels)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/:vmId", wrapper.GetVirtualMachine)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/:vmId/utilization", wrapper.GetVMUtilization)
	router.DELETE(options.BaseURL+"/collector", wrapper.StopCollector)
	router.GET(options.BaseURL+"/collector", wrapper.GetCollectorStatus)
	router.POST(options.BaseURL+"/collector", wrapper.StartCollector)
	router.DELETE(options.BaseURL+"/credentials", wrapper.DeleteCredentials)
	router.GET(options.BaseURL+"/credentials", wrapper.GetCredentials)
	router.PUT(options.BaseURL+"/credentials", wrapper.PutCredentials)
	router.GET(options.BaseURL+"/credentials/capabilities", wrapper.GetCredentialCapabilities)
	router.DELETE(options.BaseURL+"/forecaster", wrapper.StopForecaster)
	router.GET(options.BaseURL+"/forecaster", wrapper.GetForecasterStatus)
	router.POST(options.BaseURL+"/forecaster", wrapper.StartForecaster)
	router.POST(options.BaseURL+"/forecaster/capabilities", wrapper.PostForecasterPairCapabilities)
	router.GET(options.BaseURL+"/forecaster/datastores", wrapper.GetForecasterDatastores)
	router.DELETE(options.BaseURL+"/forecaster/pairs/:name", wrapper.StopForecasterPair)
	router.GET(options.BaseURL+"/forecaster/runs", wrapper.GetForecasterRuns)
	router.DELETE(options.BaseURL+"/forecaster/runs/:id", wrapper.DeleteForecasterRun)
	router.GET(options.BaseURL+"/forecaster/stats", wrapper.GetForecasterStats)
	router.GET(options.BaseURL+"/groups", wrapper.ListLatestGroups)
	router.POST(options.BaseURL+"/groups", wrapper.CreateLatestGroup)
	router.DELETE(options.BaseURL+"/groups/:groupId", wrapper.DeleteLatestGroup)
	router.GET(options.BaseURL+"/groups/:groupId", wrapper.GetLatestGroup)
	router.PATCH(options.BaseURL+"/groups/:groupId", wrapper.UpdateLatestGroup)
	router.GET(options.BaseURL+"/groups/:groupId/applications", wrapper.ListGroupApplications)
	router.DELETE(options.BaseURL+"/inspector", wrapper.StopInspection)
	router.GET(options.BaseURL+"/inspector", wrapper.GetInspectorStatus)
	router.POST(options.BaseURL+"/inspector", wrapper.StartInspection)
	router.GET(options.BaseURL+"/inspector/vddk", wrapper.GetInspectorVddkStatus)
	router.PUT(options.BaseURL+"/inspector/vddk", wrapper.PutInspectorVddk)
	router.GET(options.BaseURL+"/inventory", wrapper.GetLatestInventory)
	router.GET(options.BaseURL+"/version", wrapper.GetVersion)
	router.GET(options.BaseURL+"/virtualmachines", wrapper.ListLatestVirtualMachines)
	router.POST(options.BaseURL+"/virtualmachines/batch-update-exclusion", wrapper.BatchUpdateLatestVMExclusion)
	router.GET(options.BaseURL+"/virtualmachines/filter-options", wrapper.GetLatestVMFilterOptions)
	router.GET(options.BaseURL+"/virtualmachines/labels", wrapper.GetLatestVMLabels)
	router.DELETE(options.BaseURL+"/virtualmachines/labels/:label", wrapper.DeleteLatestLabelGlobally)
	router.PATCH(options.BaseURL+"/virtualmachines/labels/:label", wrapper.UpdateLatestLabelVMs)
	router.GET(options.BaseURL+"/virtualmachines/:vmId", wrapper.GetLatestVirtualMachine)
	router.PATCH(options.BaseURL+"/virtualmachines/:vmId", wrapper.UpdateLatestVirtualMachine)
	router.DELETE(options.BaseURL+"/virtualmachines/:vmId/inspection", wrapper.CancelVirtualMachineInspection)
	router.GET(options.BaseURL+"/virtualmachines/:vmId/utilization", wrapper.GetLatestVMUtilization)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x96XLcOJPgqyBqZ2OkmNLlo3faE/1Dh9utnZZbIdn6Nvaz14Eis6owIgF+AFh2tVcR",
	"+xD7hPskG7hIkARIllSS3T39p7ss4shMJBKJvPB1krC8YBSoFJNXXyciWUKO9c/jBVB5wVK4gn+UIKT6",
	"W8FZAVwS0C1yloL6P9Ayn7z6+yRhlEIiIZ1MJykR9T8/TidyXcDk1URITuhiMp182WO4IHsJS2EBdA++",
	"SI73JF7ogWeEpqrZqwmHf5SEQzplFNj8p2pI1Bj/7u5uWjVVkGjI6lnZ7D8gkZO7qUHqWmJZii4+CaOC",
	"ZXBqxiWMdpsA54yrHymIhJPCtJrUXZBugfzPbeTvphNRQdAap+QcqEQWEpTU49ou03tSW/XaW2FOca4w",
	"+fvk1ExRQ26ocuqNGmly1pisTXoLZ4j4jl+aOL/DfAESqY9ozjiSS0BYLdP2cPVWXTG0j2PrUz9uGoFp",
	"gE+CrFYUGUmw+v4rEfIKRMGogC5P4bqh/jeRkOsf/8RhPnk1+S8H9R49sBv0wBv9txXwFYHPk7sKCsw5",
	"Xk/a4DcmGgC5GrQDbmP1Wv/0RxjaA2p1+gfQLQI9V/kpK6nsdn5b5jPgiM3RzYVAvKSU0AWSSyKQh3s9",
	"JKESFsDNmPei/c3FINUtFk1qOBTMxANrcXPRXQWSdtG/uUDnZ+NJfXMRoXALAaL2iW4ZgvMEy2T5vkix",
	"hNdfkqwUhNH4iUEWXKOkm6YQQKIaREs8QJIhAVJLBpxlamFrgGeMZYCpWb/zVERIItQgpQZxMq2XuEOm",
	"xjJufkTlhP50NE3JCqbub92TycA5DVAiSFygyTLH/PaqDBxGCQcsIT3WhJ4znmM5eTVRaO5JEt46KRG3",
	"1+R3eDPzKOBtg7Q0UF1D0hyUlbPMG5HqnaZ6VCdiZy6SNoYgVP7wIrj3iAQzaximHOSSpcEpCkz4W8vc",
	"3Y8cirON8REgFPedjwVesJIncIYlFpLxMCRSH3EDbZaclYtlUcqLk0KMAja0T2vwPep0oezC5C9Dg0+a",
	"TNEBtFqfqcePIV4+xQWekYzIdVT/ci0IhL6yLINEMj4knn8rLB71jGr+OeOQYCHhvgMQKor7A9BarBob",
	"f+AGlF0itsfw6RUkeVaqkX4GLEseomnKxWuKZ5kTxHNcZnLyao4zAdOWKP3bEuQSODq7ukY7Z0Rx7qxU",
	"qvgVGO5C18kS0jIDvouIQGAGtjodESgx0ATFd8q1+tWAYvKW0fbJ+WqipselZLnRERpqYz2DUxx/LrNs",
	"jY5Ne63wXWIuCW7/9QLTEmeTqZnzY0ByLnGDUiHKrK6LJXBAvxyjnV/IYomOV5hklgN6aYL2KpwSDRsH",
	"ITGXQisy6iws+YqslDazZEIKhOeqF9b/QnNMspJDgLB3caZ4L0lGfsfha07C6JykQJOA2qBEBkrYCjhe",
	"AKpbogJ4AlSqv+4c7h0dHu5OUYKzpMwUkREWaHV6+X7vM5DFUv3BjTGZBkRdjr+QXK3h0eGhOi2p+ddh",
	"QGInRfkJrxYBXdLCeHr5HpU1ugFAtwFCjr90QbgwYzwRCMWPL7sg/PhSLt18JHsKauSQ9y9IDjnj6yeA",
	"ondNngyKUcvyBNC0jw+7b2reqRm5XsQahZqkU19ABA8ec7qFZYuvtXYEKTWCvOqPPmOBbJfJdKSWG7oc",
	"1SAhBbgkcwI81Dl8WfK6b3hpGtSLqpGPFwsOCywDNgJ7Toi+O29KhCQ0kahqHNJXv3fym4uROib7cK1b",
	"6RNyhzJ0yok+PdWRlACnYjeIP2X0YtQUlNG99jRYogywkIhR6EwYnk8yiTN1a+0avtQXRBs2C9JegMCY",
	"IU6rV9WbsUHMNubTmqf6ufKU5QXmRDB6RubzgA5JcqAiaA16twRUfUYzUPpLooeD1FPSNMABaD3yB1Uy",
	"RrP1OT0eUsebCFziBdSdT+7TubUANQFqkOrxxxL3usxzzNfRe4+zDrZOVCcyhNYpZ0wuPeYR++icpvAF",
	"HSrl8xjtzLCAjFDYnSKiPxypDyf7vlmknxpdWXWnT6Bz0/2ZPoDqfzQtY+peOZ93sXhb5sBJgtRX4EAT",
	"EGjnBOWElgId76LPRC6RWOc5SNVMgNxTTVGibGhCnZM1m+1X4g8tsUCUIbsmB3ZFFLJx4TqeF15Tyddd",
	"iXWPAToi6R5j+GJm4+4tht6CAAnfdjUPWybo3xf9FvPWltiQdQcttv7wPWAyHjNkRLxEr9WfUQ5CKJXu",
	"8xKMjbMU+mqo+/T6ipy85IDTtVHCtANCuz0c0K1/ILNnhDYHcdH4bISwnnesz6iBuPnvlYUm+PHUBzHS",
	"woO71eLCwN7XxPz3skKtbw7r1Ao0eG2IsIEvK7SPukcjZBIHbtCVmPOl3D66ZIJIsgKUA6YCnWgBljMO",
	"+0HNwjv+2rpWSaXTKASWRMzXlSOkPo8JRcdoVkpEmVT/OOmZ5eQhs5z4sxwPazSGbMNU16dxh+iF/WvY",
	"s6q+Wp0riK76HvEutfU11VTEdb4xCp92TmidjwiUESEjvqk+3waz3RU4++h1Xsg10nLNSBiNMHxJAFKB",
	"Kuz2xztCgqfDxFBq4hPMARpcOK2fvuGsLKLOoZZjMcdffgW6kMvJq5eHh/eOIGC5wrOQ62mOv/z08vBQ",
	"IzQnmTUE54S6aY4eHqagfUB6BneN9NBw9/Ntz6cxO9KYhX2PFtvIwujrGM5ih1nJA6y8OgUqgaP3V7+a",
	"C0s1jEAzyJiSAyx0mpUCePiG7YasWoQ8vzgjPQZYHwrMAWnPRlqZhznIklNIFdT7YWupTzyFuAewmz1E",
	"xYZrp309ErfnYe/VnAMoF0FC5PrNSdj5tcQ8/Yw5HCcJZMDVJe+CrXwXkmdFV9bg8wB9zqsbtxI7ihSq",
	"pZIPHKy8dggoVQRLiZUpfzKd0DLLjFYqeQmh6zpLIYu435hkCcve6Q9fQ4oN43gB5+xUGZMWZe0D7NPj",
	"rsO9nNQdoqeMQbMCmgYdmW3xp752J+usZjXi1LFAfDFbxHJU7eW0M5CYZMNOtLFSfjpJHPCzka5ShfHo",
	"xhTjM1iRZFOoaMy9a9nnWDU8T/uaXER51Da4ia19zS/to/fn6yl6q/5zc8OyKWIc/fbul9dXg3ZBX7I1",
	"SF6Rs3fVLzHh0QNUbeogEnEabsV5HUZx2OUcxBQykPArnkH2JmMz5QzriZyaz41aPxAJJJdYoiVOtejL",
	"1NiIQ85WWsR1ZYRuEbZmmc56PGUZ7YwSIYkZcVoDHEL9tZAkxxKuMA3ptTMQ8hSLkEfOCkFkZkc7sL/Y",
	"Rx8mR8vnh/mHyW7oJIUvRYR0sdGeLY9exkb7zPimwD1fvogM16JdhbcHtD9jiJQ/Wy+62i7xaM+8ULyW",
	"XpVUhA+LeGxLdKsNRqScrCWId+6CMCLApOr0vsgYtjFTWwpM0SFWvmmhAKNimmmx1UptJN1kWhNN/cZU",
	"HWM9RoSxoS+KGrFVCFzJYfPYluZi+1P2sY9inRDnkB9f/so+A2+sRPzoU+3fF8Xo9iDkJfCjd4PG6abE",
	"MIbY0dFD00kOmG7UPCWbdSCbtO7dOQKr9asu5gFul+kZrO4bOuVzkzeTR6IG+jVqNckbIEw9HvHX31/b",
	"PsaDqNRSkI43egbkYEDF6kgBZ2B0+/7jkIz2d2V4S+mr/3ZCGPvij3/TP3CGFmq+oRDk2grQHOVn/XcE",
	"XwpuwunQTnG7ODDN0dn1r7v6MNKcMnk1sa77D+Xh4XP4Cf3rmxOEaVrF9vyE/rngLP3nsa7S95T8owSL",
	"wX181W8M7kQUGV5Ho6hNQOxGpB8ZeJ2rkGBjCnRoWEqPc2YOWy00hv0+Aj3v+J2iRwxtDmdOHDAV9hgB",
	"B1C2gE7jhrUoBQawH40zoSugkvH1UI/zquGjUGazMPwbwmWJswusmA0G7ZaGJGaKTYmt7ltvQX5m/DZk",
	"t1TX2sCmMB2Q+a73ISJUkBTMxlCDBmVCEbDgXCKcpkoahXrkOOl2uTg+dX1U7J0AoGi27p+a1jiGcdFI",
	"zDnL+8cpOMxJZfeMDWZaoUw3Qzun52dXjQgnQuXzZ2GZ0VmiX4iQbMFxbqYr1LmnrzfGbtVaMSxxg81i",
	"dqJaDOSE3uCshJj2AcWIrV4NYntMDSQhlvuFhW74SVGeMg69YUAqvi/RjaLmOw/ypCivWXILcnBMYZuN",
	"GbXnWKsPtDoKVt+mQnytD9aLgPNJkceFzBGKLk4m0+6daBjOfNAylDMd+V4WBeOyL/jX2iXR6kL3UHZU",
	"4XpVPhqFKNpRwF+vhYR8v7LWrffdjBfNGXfD6S5xi9VqNMj3BnWVD8PYzntxxtC4afOczjmOh75dAlc3",
	"ukR7CTbcvUlRqoS2U5bnROYQUmEUi6s2SdUGXWFJ2D46bcQw64MDHWcZ0wJGxzQLdICMc+9yuRY6JuzU",
	"7sARF5/K9j7+6KuvtgFk1cpdqquH0vjNoDhNiVGMLxu0jVKuXhU12njAtNiKwKRW0Aafh4X0JuJYb/2h",
	"Nb06vnBC4j5La7u6tbX/xCaoP4Nxq2uP1PEkdHpG+KJGU5wxCorO4gwkJL07HNO1TRjgJdVhVKyUyHna",
	"3AUlxxQvQNNlhzLlI+fasa962zZhKWScII3Q1PaaRrS/eieLHh3xF8d7QUVxi+xkRlPT2RD1eOz6zQVK",
	"gQoi1zru7PX1/yCaxGFmUtehA+QhM93YNtHo3N7bHn81BElYvuo0oyqPO6TJKp9SQBP4pcwx3eOAUx0L",
	"a9shPFPspP2/NryCVHMgZxPomp43io6CweConmiPADhdS+d9rZvBEKk2kdV/4bKaK/j5qgIg+PnUgyrc",
	"oAY1+L0nugn6OCUe4BYhe9WvQ+1Bi1IfMf1YLXDhZsFvbnS1pdP0dvAGmaa33oG4CYG8C3OTNKPv0iZn",
	"uh6pPXs9UC8EZ/YuE1Sa/My/3uDIVvO7KrizlSY2YhC/h7YtWK2u366gGqlVq9W73oUzJ5hnMehtfdFd",
	"W2MFMMAF6StECeKEA75N2edAGgtOV0TYZe4zhunY5UbewLHtiYiaI5KkYVILNh+8SkqIDx6Rv0MjG/kc",
	"H5ZQc7IF7bJDg5/XnXum+Iy53t8bD/830zE6dDsA2JG/nrKJ37Re/u7xUDPRhUvy19wU4CEhQAinu3YO",
	"tyRuQiPhgIfKcz3SHV3P72YLoRG3fK3EZyKT5WZBB+YPtbfBaLXc1nZxacWTaT38dFLS6oYadDOuMkwj",
	"QSCrXERtkeHYnmiti1Bid4coMJQmbKPS/GC1JV4BEuV8ThKio1Q5WZEMGvGlnt6dE6HCnS/rVp3JrgtI",
	"yJwkVVJyPaQJX8AckB3n/rGgDtcQsZTPqY9O9w9U6vcUPkZIy6be5qHE/CZtogE9mzn7gkFCQysY99hd",
	"cpaACCh/YaeTIo+LLixs19BGBR7OFbsxHwaHCAUbhcC/UlnmgvxO6MIqJj35JPU1so/A3SFbug4HJaI+",
	"BYVzC+66aaVqjUSjP3HftPkUOR/c56hsbib+j4ltqJPvR7a2OdkjW9vc6RGtVZTlyKZegvrI1uOB9hK+",
	"R7TWl/tPBWcrorgf0k9JUfaZRBptFcqfbmf3nstYtD7ls5iN5VMy8uT0+K7FZd4w0welnOv1bXBolHz9",
	"uPZRMrQFryXmso7MiErrhFFjBknWYXoOFV+qCvCImFt1G8dBnZ95dO+zQZOktjVESRLPXLlgVzB3tbms",
	"meY7Kc4VRjgWq97hgQUI9e3dkoNYsqxZWef5Ybueza9YKo5B0rVX/qycZBkRkDCaqnyKNaMp+rwkyVKf",
	"jdZTZLN8iNDlIkkKWqs0AEAaLwzxMnjj7ALeLchT1ajpVOW5cGV46nE8jFwVGHN1cnq/P1pu6u+EVHvY",
	"tECR88SdH/yGThmVnGXB2jupr8N1dGxbfOO3+SXg23dVzasGGD92VvPS9NLpYYBvUV0sa0yhjl4Pt7EX",
	"tVOockJ9l87R9M+TVOVN8jRZVa0Jm2lVkfXosQTqIqatOnJlSdJgzMc9InCi9sJpNfXHKNw6wv7mQkRF",
	"N06DFSa1vMapH0ov2SMI7not2jJ7OjFR91HozGcPQBWv8qQghtjFmSwjlTwHq8mElvLmwkQqmqhHMb7E",
	"bDsf2RaOSa1D0a+Wiow1frpJIlG0WM1Zq0TNfQY3xVZOsYQF4wR6ZzFtUVI3vsdUequMmSYzDTeZIm36",
	"QWPrUrXamGBhPd15C93UbVxDZJ4O1w++uTD9+yo3lLQ/1Kgy4AJOlnYD7whtXOApcOVaNXQ26s/uZCNH",
	"bza0lnZs68/MdHRRKeD+FM9qimrUw3RzNRR7HA5LP8KtNwajatgfa6k//cx4s/bImHZ/I3JpTeqiv89b",
	"JvuHjySXB2AbBCQ2a5ji0YygL0Suq/KWVm2Kxc/0LYO77b0jwF1xn7tpgO/cRI77Z2tUVQdGNUwogxVk",
	"UwSUE5Wda3aJRlnFet8iQX4HHZOgG+6j67IALiAFgVJvmpP1aTXm/iRAGz/IsN+t1uVae8utZ1DYPzkF",
	"ccKZ0Fjf7nkElAS4ULs5dYGwYBJoVFegC0Jtob135GSKjg73nplfzw73XppfLw//5R052d3/QEOEM5hb",
	"g8k9Kffm5AGdHbG2TPAgoipTWTxkIjXAwCRBnt0snq0bFvTADYh2Dn96X3ujpujop9dYrKfo2U8XkJIy",
	"n6LnP/2CeTpFL37625JIeJOxFexOhlEsyqHFC+E3cjOo+EZJgKNZqeN4TSLmFH2YHO69+DBRP17u/av5",
	"8ePe0Q/m19F/23v+zPx8/uxfPkxGoHGhDW2PiImZYBiZEA7P936w3394uXf0zOJ79OzHvWcvbfNnL38Y",
	"h+hbklS7fZtoztbo7fmpKW7mIWZBtUBafMz/XsQAJt0oht7LZav5nVen3j/vR9kfW87vUGq/R8B7SDzq",
	"n/JXgMUm5cCGoWPioZKmsxxMqDiH+wpN2zskK4uthftynN/7CBrSNUcpmhtrmarZz8oe945lwHGwZnWw",
	"HMAKkO6Hqo7ORjiZ9k12dXYxfoZGGArHn102UI6LQqfDX51d7CLr2+iZ9HqJOaRnRNyKe04u9Aixqfr0",
	"8GbRP6cdOl6p9BZfAWqyZGSvhqRLUFk319S6VFHw7YAEeCAE/PL1xR7QhKWQotNjpBqpsAgsAc1KmmbG",
	"ar0CTlz1Mqjio9/9eu132EcXpUo4y9YIzCMlK7ClKW9J8S4T+5OHmx71ShRYiM+MN02H1R+nj1azyuIR",
	"qwyshFqbKIZ0zlZEhKZFAakiljBF32agX3CRTI+AVPz6QmfBmTVD/+///F/DswnLZ4SakUytJoFeHB7u",
	"Iz29IpGE9BUic9eTqBBkAdTGIHuPZd2SQmhQG+DtzHBy+xnzVJgytJLY2vz/1hxUewYVx7SGNYOBGbkU",
	"hl+wbNBDYWPpiChAWpPAVF3rehqGCmz5MeMlJ5OHr7ia8a5VjOtxeGqopFbF1CpktxWO262Asrbn24jq",
	"F3kaqLmepy+RKHMXY1LaghpIYq4qzWwUr6KqwVSJzi7I6jTT4Vuu01DwSt1OgRsUfaaFUxtaSb5EmuyX",
	"QAo40dspJxJd/3IcQqwkb+Ld35+jxeAIUdIcL+5HhBqfJnhBwjSTf/tCelqpAZ7lOYRV2sgx6z594dlh",
	"+x5YilV/rC010bTFLjPXuezdmCuhuNk0MG7NmwvDlxsau4MPijWIjM7PFNBWMoW9WC4i4NSaj4fKBdQ9",
	"qrLtVbm+DEsQEhWKP4SEFHEQyu0aDj7u5rb0u9Fa7d1laRhi1UoBWVLPl9xix2hVqcAivhfA91KYEwqp",
	"Mz/X4174i9jv9SywlMDVkB8+XIeWZyturrZr1OXiBRLQ9d83Zva+BwDeKQWCGOndYk4i/EcBFAEv3t1E",
	"omeDj9CNCS1wG4wIowKqw0Nnw1djBmeMvL/XRCAmURTxMyw3pgZGVc+g1lGHEX4a8dyPa4D29pApkWOC",
	"utABclW5PjX+/gUp/hiVItkAJfaSTvvZGixRjr+gnf+6+29OCdQ5Y5Q1milxfj8ogq+2BKAofnz5SFC4",
	"iMaOyei2MfjjTB5/Pqf7UM2jrkX0BZ0wINtdDnvYnZ+NKapqG4dOBFsUV0Sq4tqe1+G0OjeuSYe0FkF9",
	"v4b0N1r/nM+nSJSiAJo2cvL76zTqgJQazxYwdXRyQzXyFJ3qAGicoMM6W7SA6X01t6TxTjH0vtJsSWm7",
	"KDO+/6zwFDFeLDFVvwjFSQJCkFkGu+FpOajsYVNGIywydBvtm1sZGthqGmOqnWiTy/F8Tqh1frQMHFXF",
	"gcv3Jp4yeBoUhCr9ohmrM2LuQCWF3vLoDj9VFWEcdg9VuANFZcdXDTIlaUOIps7Udp9RleAOjDlvmCkH",
	"3xNsWyfrIMbgiT4nPFfVhUP1zMwXpDqhnRlhAjGOYE6CHD1nWRpajSr2DJkWiIN9xyA0ii4OdB4MItOw",
	"6O/ot+uBEme62dtwnTM3wrzMsiiDLLziTRvUA/N6xQpaBHLYXTWAftIsWT9K6nsMnU1K63QFwcjr22bs",
	"7geCqxua2NqNrDi2Ra8ihCo4Uf5j1F8ey1zZ7rmXo/6hP/l97uIkqnERinJYYGOOGyXj++509d2qw64J",
	"psp0anpHpN73cps788otOoUwZhXwC64JCekvN4NngWnojlenyA6cCJQk92X7t+enwdTLyqvT88SKauM0",
	"rHuoqTqEXalcodhOVfRRkbdqUgetMhraY30ouxTHYKkdnUTwXoQWxWUYJIyKMgedshHaDRELR/xG37MX",
	"hm/0krFM2BIYtcwNT2DP4Heqixq6roHSlTKqTWy85jhUSJxluNKwy6A4LseXlLjJvWzHM1udRg1RRo5B",
	"ZUzWHrqycyRiIciCmtivnkPwSW58PVVP/ZuYt9u61xtPF+9cQjwh7jRZKw3G3MtcOcvmveyW0FC1eN3a",
	"KpZJylk+RfOMFcV6ikoxmyIBnOBsigrMcZZBFr6XDsFkLSEtf1CII09KYaERiSBTxQFTJLDEU0RXeeQK",
	"Z59hiBhb3OcNt/mcZMEkhbN/V+VwARVYLt2Dn4FcpBq8W1hHdT7tT7iFtXZE28E6x86YE7pK9uqgrz6h",
	"HWeGp9K8HanFN5WfYn+njNafglTnad4nAYkwMu8Kf0aWyy5M0ERQ+pnwhn6RqomlfNS6LZqB/AxAUV5m",
	"khRZm3Bi5IPqMWXY+kBCsQo6qH7dX8KjdeQsGbfR6U6oVfEK1nMSrqCpy2kNZ5i4htMaOgfLxw1wdheA",
	"AWO3QHUX69YR3Wc5DVr3Vtw7CxEK1R/CLFy4xV9Bl854WheN+VtVNOa8UTTmuC4a89pWNPtNMefIclgB",
	"0Gx+xtqbvKdVDVdPoybIPQ09bHpaOUR7mlgaDNV2N+e/CmGq/2zibxJGJXyRuuo6B+W1Bppi99zoPbbY",
	"6AddvM3iDza8ZfqLl/+B3jBs7etG7fdo1ffpZNXs91hFv1ddib5J4e/unShQ7y2FgJdERfDqT70Hc+Ac",
	"Hijlfa+q3T3GqGERaPJFo3mim5hBdjgUGU5A3bd1wtXCftl9/PRMyuQsw/Q2ZPAImxCCWgRzpoLKejBk",
	"MbhXDGBwWUKXoVAFgseu4GICM/7sJV82wvIxa8TkLFLNZ1zZmPsXjNmsVEykplBbz2TG32jbB5CIzRvG",
	"ZKimjMevQwVmvEUPVZv5GEmEaidMdXakPnF0q5NRUWHvTmp7sTRekTGe6nFvsxDaGHhMGLgFvZ7iY09K",
	"2KNQQX/QU26TFJE4eT0Zm1symUkHyOQmnDaw/NibARLIiw5vLZtq5hKqWu8dXbvS/XpFtYv5ClL0C5bo",
	"30+vEeaSJBmgF8+ev3j545FXfcXGLGvLsSnO/6kusagYP89L5XFu/FXdqAjOPi0xTbPwy1AVwJCGH6kt",
	"iwXHKVw19PRA7Xb3HVLl4rO9XGAX8gpCqs96La27wDZNdaUK5DcbVOtdnapQsUm3iHe21qnGjshMfTsW",
	"NkSxSitCJgj2+PJ84kXKTlbPNBcUQHFBJq8mz/cP959rNVQuNSMc6NId6tfCBBMwV3NSuVInb0Dqga+d",
	"dZXbO4Tu/Ozw0KoA0g7ipewf/IcwdDaq9JCi7U+jcQ7F+IrKVffSTN12GEvg6jUuAXwF3JbxvtM8YsWE",
	"wghhf7DpxKhGfzdz6HthwUSAGNeWGLpQkVlIEPKEpevtUkGNXxXQarKM5CXcfbtVUJChZInpAlK1Ci/C",
	"q6Afrka8rgH24vDHYHjMPCOJfNBynmpg7IrmZmHa63k3nRwkLMuMdcbeHTKQ0F1i8xzsqde4Q+wXIUuB",
	"6oVwliF/nofgFRmyRs6HUbFscPuqW38vMtvjnHqahqkhwETOpbYtUunxxhKqxQsaE8zh4Cs+T+8Ovs7O",
	"07uoMDw1bZsEVX6GHExBlb93nANYQKY9y1UfpD0thOoMK7l0jphXE6yf7G5u9alH/M5J0t1PCjwiGEWm",
	"ROyYWWcbzvrxSVioRqXK2O/ykYevZQZjnSuA73mY48WCwwJLENpel5L5XBiZFNjJr4l52L/uTpk0wfcP",
	"E1OGdZD8zHw21dlbLvUsCOgD+Pjga0pyoEoT2ISnz8h8/p+Pr6fBfCuQnCRKr7PkDc9Vkbl3RqcIO4Ng",
	"7me5Ukb38lAJmTiAl7VVFu0c7c2wgHR3Hx2r7Qep7xvL1goFRrP1OT3WvGV+n+w7fP5RAl/XCFlbZQ17",
	"Fd9y5NURPArdU/quQDpctABuDMrqhyAp9MBg431rOHrnfmrRpDdKQC5d4gWh+lkei7K+LKjtDLzyAcpl",
	"Vxi4ILoFWQFFNVcNKVpVS7TSr/09tXA74yTLkMrK1/KsD+sAxriD71iZ95WkdwftUnNRPejYbzgg306H",
	"BQz5fs5ND7Oxuleo8l78VDzdNsdoMIIwKFMM9njEV+cb5eDC3ODqzR18tb/UOdgKAIpddAP1zp+cTTry",
	"02X6mvrFOhcDfZikLMeE7iVHz55/mOwixtECKOigxarUYQyiijC9gNXBoP9rx8324UP6L//bdt/7++He",
	"j3hv/vHr0Q93u/80mT4px/cU2w8pipYi7ZSc+mFZm/pZvceFeD0BMqXzB6VwXZIcWZvhJttpiijz59dz",
	"TtXKuvXczs5T5g+HbYAss3WTf9ze8wge23rwRZMptsFe68+n/sb+1ntLpXvjPQEKDkV0gwESCSvAK/HE",
	"VsBXBD5PV7mYmsznD5PdfXRmlCJdA7Zu9WES06r0uJONIPytlEUpLT+9Qr+TAu2cXt/oeC4rKv+nikXn",
	"yZKsQAuCL5n4gnZef0kgQ8oZO2Ps1tyLTFEWAGlULwXNbgRUM2FYBZz8TgrPrmv+pWadfHyoEFjRdJ8V",
	"QL/kmYFA7DH1Rg2kLClzVdBCFBxwqrHIs339/6bUqMz1qrKHRqlD5MaUv5Ni0wE68sVbAh0agol+/Kle",
	"KMZRc0EGhYnhlSc7j83m9DVDLR+x0Ej4+HVR2UhbqysLRPW0N6bJtxcPptaxq3Uws6H2OwkWsEeo0I9y",
	"Ev2O0swMYoJRYntqtnYv+owHoXXH0wEekMZmeJRrm0XfXds2ua1V0z87jBajf+qLnOausVqy5dahzWrC",
	"jtTxwUHUN7YnU6SV7dMuU1x7ttuqd18efNX/77OBvgGzQb+D/anhiI5uMXnYFNdKKs4JZKktEp0SbrGq",
	"1AM13yssElMa0WpPr9Q4Wku4sSyix8Dc1F2YIj/peep0rilyDv6pff15aut/TFFSlO8FXoBpY39ynNtf",
	"Kmd3tdDdjlcLpYLAF10ewavCraC0BNLwqQMbvhSZDsU2tAnqLYw3VYHxRV6EXGdOn5j0izdlCiiM5cQw",
	"7pNJOI3OvQTct5VifRLM7A33brJm3Xaw+QgZxezpt8W7hxlvtlbFfTRYRIpQHPwoqdV4xSImruoXLP5U",
	"Rh//YY67aRgVbQaumo1a76r9Ftc86UJjLX/Bk8phph8zDC+8DbPNvWjeqD7ZZa7vRLGcrX2VIaY0vvab",
	"/HV0/XV0/cGPrp60hB5NPHh4DceeIG+rP61O3gK4RzFvozZO5B2YS8ceK/o9H29Atl7t+XMdg7EniQK8",
	"ZBoiR7En4wcdcbbCJDOV4nwojMNOPJwb6qyIOBdUb+38qZa/9QJQSIboFi5zSz+K87Rrn+lQ48Z7Pz4w",
	"D178r6t84MreSQT61ipQp9JneBqF2PfDa6FyYgF+a+GW1mUERujfrc7b48IIVFtivrE+1puL78u92qKK",
	"eyX2j8CNwVIVAW68aPo9x3NjxXuKLwMVDRtVhh7Kng0npHvkwd4SdRbAnCTo5mIsvzLeF+V7LVlxWjUc",
	"E+FbtUZCsqKAh+1HNT9KPABaHhTG4yG9KlDBtXr8qPz2VHFbA+Pbis5P2gPG6BOJ0peYy57VffYNiGML",
	"1OgMj4eHzVdD4owDTnWdkIKzBQfxMOpr0sXuKT7t9U5rPo9R77V2Xk3OViC0FiQk45A6AwLyRqhDMZRk",
	"UbGMyg4QjM33ph21c71JDIzpNgLzLSpJA5qKVN5fvY3cJowJ++2MhHKQWAvYnfdXv+pYzd199BZWxsfE",
	"BOhH5bip/MWRe9NgH71b6gJdacEIlShlILQQ56A5C0tokBwvMKFCuscEugRXoqaP2lsUM9U0PVupJlAt",
	"aIJn2FvWwNMQ+MFiqbtOXfHUWvfq/e7GgWzXQvQtxhQBTfi6kJXxTtyaEF9VfGeqg3g1QMJV9MmYKsrq",
	"do9y3au/4kS7qH2gQe6jY+20VoKGSnT5/h1iK+CfOZFguhUcVoSVIlsHGL3LKJdlh1G2nxoVeJXniZOj",
	"NuNSgdyuS+vl0mz47PDom8GUcAhA1B/Y5nVnHJWUA06W2phhJflDlSEOoTMhurFap89BggusH9YhDVdA",
	"iwhLSG6F21+o4GRFMliADULOMlTxtFCFmu1hN3VPRqifc8YhwUIC37XP8QR2B7omdJEBytTGc9MlanYT",
	"46f11cWAtD31UXpMlnbzrHvYp2pjJZ42OFfAP6EY1mtY0bSCACVNasW5pl7APpVFqedGDtoyhWgGNFnm",
	"mN/uo2Ojc+15sZolNe6RgoMGPvWrrIV1GTXFzzUwj6ik1rPEV/jEoadSmhPIINV19HQNNJOdZLKbNeZ9",
	"613Rya/x+KAV1/DU43qr65FvUMeyz2tXSJlioVW2WIEJrzRod0UO7tAONR9xb45ZOVeiqWbsbdzCLlmW",
	"BYaM0r4IFqfWtwmBsFjTpF5BtZ2UxGVUK6854141QqRWQoS2C+aytV+2r2G0ZtkoBftbbdixt0pPEk+d",
	"YqJEp17+qblGEI4ykhOpSg4BpJBG76DHlOlUosZ+d7fRbex7cxMd3PZNmd5RBMJ8qTK4SgkCfV6SZInY",
	"fK6eZUM5yCWzju45YP0Ag+bUyvxkniDds0mILaZFRjvXr/bRVHWzdTKcpqUcxtq7jCQrWMYWa5QCJytX",
	"BFoXMGP8NiNzuRcImQio3Ux47HqJCe+oDdvfJI1p1o9YpmBcReUGNIHybHFthoDznBMe3T5n1SJvLw+4",
	"lIZlYmpLH4dXTBdXdN2ZVzcdx1/2aVHLqZaJFfMmtf5H6lqNTeZ9e3zsXpqtSyAPHaFnNTJPwSvVdM51",
	"M8wsVbpcDWmMU976mY21v3cL0b1uKB+KcdyiBdPBV4pzuOtTeI2WZVTeWqS3jO+aZW0UvDI1ga8hqJUi",
	"tIRK61PvhJkzwkhHJVWFVHmixiQxpBKrjT3kH1JtNDjK2mHhrJVvfTJW1tSgQ0f/72EOnc3O/XbVTcLf",
	"hquYTSfCFb2vCihZ1TyYHB4qGhQgVjXGKB3eLmWtHdQeoYPqtJ8TSsTyoRc7o+ZjJMzduTCrP4bH1e1r",
	"UBYSmpIVSdVDQTV6RLr7/j4y4SO6krsJ0DB12wvHYQOS7Kocjqux4Sf6tugPHY3asszxmA7GUXKzUjav",
	"SrqJ0Gww0hZKvLTGG88e2nE9XPWnsZxDq3lV3tspPVjKPbCsga2qIPAcGv0+JQNtbNerobZUCsCWLWou",
	"1si1UiJveC8nRoVK9a2UCEkSV0egqZH/s/CBMDW/99GlfcGn8pK4ogvvz5FkKLWvqlT1VZEkOSAQkuRY",
	"whijgBh/bEmGFiBbiAzLg+8jAMFhbXAOyIF3S87KxbIofQyjrHpBhLaoOjzr0M0He25kEJAenhyRpfir",
	"4oaRuYp/JRL+lUi45UTCt+06KlsJWrZL1C2L0JdPGIvDONWeJm+fPJJBwsxjM6I2sEYcbZcV4llY1uW2",
	"WeDHU6y5oRzCiMJns/aVM3nMwteSspk32q9lNRmiV25uP8FzlGLlcuc81Wp4NbacKmf1KDPkpvsxFjf2",
	"TUn/V4LSXwlK/+lzax9XaLTzazc+x5XW2ZUc5kGOby+3t686GMw2Vx0On0p1KDWAW1cdtsx3hoxb0iDG",
	"F/TTw2xS1e8p9Ik/UFW/x2WKnhJ/tuqjFSVBrqiCrobC+OtX1yaPmmxvwYm75KsmfoZAkO51S0Vpz1se",
	"dLVfgfYi2/p++hHerUV7s6KObmsk4Lu/9WmTbZoMbL5zap4xujk7+/c6wtlKC7dwEQWBmL43aXobMnvU",
	"ryV+/H54oI5QftJFVToAaYMRW9qeBIrWvnqkYBv/IcdvEmwzflHvkcKBdihTL7/ouE/F9/qHF4mzG2WQ",
	"mpO2H1WTAlT7XmGlxPHNRYxLGtL4YKW2YG+xFdtS7dXHD5FTs1zWPtVQ+psvbvqOQt2wLFQo0BaSBbzR",
	"BjdhGSDlZdkkZe8mNO/JYi6VMyXf05j2uJ3dO8FjSiX6j9XofuH3aZ5OYR654v5C9m5V1Tq6C9+bBYyk",
	"Wb04et7t8jPJAEnGUIb5AtBOjr+gH15cnOw+UMPWgGjUJOYznGW923VEWSRznxtdHOkalKLoYuZIXaLH",
	"xAXLklNVmDjHhH6YoB1rO9i1n4TOYtJHvWrhBR1hgf779W9vVV+cZR8mVQdT2XRW0jRrVNUMjLFT/dxX",
	"zLSro5ZgBXxtNVqd7CL9HuYv4uBDeXj4PLGqv/4HmDF0sD/KMVUxA3YjE6rsQ/ZddEgR0BXhjOaKQccX",
	"fa0LqSo0vEqq9p9qbT9Ov1ktqe2XRw0Uo9rXi44+L4GaUqeIiIp7/q1Z1bbTSvPJ/gbXmseoaVWPOcrK",
	"0q1pVb3R1ZMsb5s8pjg1U+hH4kKy1Hz24/6iz2mtAm29bG3z1SG/Qf0uI6g2rOL1V4mtvyzYf5XY+l5K",
	"bD2Ot7oF8DhBHK4a0S5qMlOW8D1jfd3TDzA7WR2+Mp+o9r6d/ObiddXrce7P3pTVVJsbsVsPxLiBHsvw",
	"/PCV12hb8LworWqNjNqmL0QZ1C/QboMpxldcczzQrrv2B6qCtvWFG66Cts0NPFwPza1RVRXtj1Kj7HFW",
	"pr9G2faX5uCr/v/ogBFNoDcZU1ffwcuqbtwIrm66evTU342jx6HpITjIKojrsiobCeh7M4gp4YKwYQzD",
	"C4ph7i1dR7maNZ7GLvktFvuxvM0OrYee1Qbt7/acPk512TAeYJ3HOZ2HiyCGLpJDzPVXncIeu8oT1yq8",
	"7yE0Stp8R2zxCKVzGuAatB8qf1okeLxIlUfhMkOD9ti1n2Tbcumg9rf1aTwmD645cMMT+50Iq3hUgynH",
	"YrIMq9ya1uaK80g0MOLFIAPWuYnaN1AB848SSoh6eI69pTXnlXbME7E1h7xZ0qDT1a9s2RY/92KykUVY",
	"3dVng1Ksf9VJHZRT30mF1HGnZOs9RzWZnt2sfcmzyavJAS7IwerZ5O5j1a+zfbTl31aFUl63nKXKPUfx",
	"AnK1dBVP6JaT0BuMjSfndO26UP+6nQiMUjmwGtvZ8b3oDMN4YJCAnwpxMEU/vCF8V060oDCyW1OJH9US",
	"4YQzYapgWuO+N2TX9Dqw/4xbM0SnNy7TqFPJIhCKVyPqLVQzdLATudR5GNUsvHUiHDS3UT2s1y8IHBSK",
	"dz0BmZE5JOskAz28CeMI4Fv7vrujdmvKhVnLryg4DbN42Lnlls98nNx9vPv/AwC5YyX74CIBAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "https://raw.githubusercontent.com/kubev2v/migration-planner/a7aa1fcda3ed7acbb05e4636f39c4d764e82b6ac/api/v1alpha1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
