// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v2

import (
	"time"

	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AgentModeRequestMode.
const (
	Connected    AgentModeRequestMode = "connected"
	Disconnected AgentModeRequestMode = "disconnected"
)

// Defines values for AgentStatusConsoleConnectionStatus.
const (
	ConsoleConnectionStatusConnected    AgentStatusConsoleConnectionStatus = "connected"
	ConsoleConnectionStatusDisconnected AgentStatusConsoleConnectionStatus = "disconnected"
)

// Defines values for AgentStatusMode.
const (
	AgentStatusModeConnected    AgentStatusMode = "connected"
	AgentStatusModeDisconnected AgentStatusMode = "disconnected"
)

// Defines values for CollectionComparisonDiffDimension.
const (
	CollectionComparisonDiffDimensionMigratable    CollectionComparisonDiffDimension = "migratable"
	CollectionComparisonDiffDimensionNonMigratable CollectionComparisonDiffDimension = "non-migratable"
	CollectionComparisonDiffDimensionTotal         CollectionComparisonDiffDimension = "total"
)

// Defines values for CollectorStatusStatus.
const (
	CollectorStatusMetricsCollecting CollectorStatusStatus = "collecting metrics"
	CollectorStatusStatusCollected   CollectorStatusStatus = "collected"
	CollectorStatusStatusCollecting  CollectorStatusStatus = "collecting"
	CollectorStatusStatusConnecting  CollectorStatusStatus = "connecting"
	CollectorStatusStatusError       CollectorStatusStatus = "error"
	CollectorStatusStatusParsing     CollectorStatusStatus = "parsing"
	CollectorStatusStatusReady       CollectorStatusStatus = "ready"
)

// Defines values for ForecastPairStatusState.
const (
	ForecastPairStatusStateCanceled  ForecastPairStatusState = "canceled"
	ForecastPairStatusStateCompleted ForecastPairStatusState = "completed"
	ForecastPairStatusStateError     ForecastPairStatusState = "error"
	ForecastPairStatusStatePending   ForecastPairStatusState = "pending"
	ForecastPairStatusStatePreparing ForecastPairStatusState = "preparing"
	ForecastPairStatusStateRunning   ForecastPairStatusState = "running"
)

// Defines values for ForecasterStatusState.
const (
	ForecasterStatusStateReady   ForecasterStatusState = "ready"
	ForecasterStatusStateRunning ForecasterStatusState = "running"
)

// Defines values for InspectionStatusState.
const (
	InspectionStatusStateCanceled  InspectionStatusState = "canceled"
	InspectionStatusStateCompleted InspectionStatusState = "completed"
	InspectionStatusStateError     InspectionStatusState = "error"
	InspectionStatusStatePending   InspectionStatusState = "pending"
	InspectionStatusStateRunning   InspectionStatusState = "running"
)

// Defines values for InspectorStatusState.
const (
	InspectorStatusStateReady   InspectorStatusState = "ready"
	InspectorStatusStateRunning InspectorStatusState = "running"
)

// Defines values for VirtualMachineIssueCategory.
const (
	VirtualMachineIssueCategoryAdvisory    VirtualMachineIssueCategory = "Advisory"
	VirtualMachineIssueCategoryCritical    VirtualMachineIssueCategory = "Critical"
	VirtualMachineIssueCategoryError       VirtualMachineIssueCategory = "Error"
	VirtualMachineIssueCategoryInformation VirtualMachineIssueCategory = "Information"
	VirtualMachineIssueCategoryOther       VirtualMachineIssueCategory = "Other"
	VirtualMachineIssueCategoryWarning     VirtualMachineIssueCategory = "Warning"
)

// Defines values for CompareCollectionsDiffParamsDimension.
const (
	CompareCollectionsDiffParamsDimensionMigratable    CompareCollectionsDiffParamsDimension = "migratable"
	CompareCollectionsDiffParamsDimensionNonMigratable CompareCollectionsDiffParamsDimension = "non-migratable"
	CompareCollectionsDiffParamsDimensionTotal         CompareCollectionsDiffParamsDimension = "total"
)

// Defines values for ExportCollectionParamsFormat.
const (
	Xlsx ExportCollectionParamsFormat = "xlsx"
	Zip  ExportCollectionParamsFormat = "zip"
)

// Defines values for GetLatestInventoryParamsScope.
const (
	All  GetLatestInventoryParamsScope = "all"
	Main GetLatestInventoryParamsScope = "main"
)

// AgentModeRequest defines model for AgentModeRequest.
type AgentModeRequest struct {
	Mode AgentModeRequestMode `binding:"required,oneof=connected disconnected" json:"mode"`
}

// AgentModeRequestMode defines model for AgentModeRequest.Mode.
type AgentModeRequestMode string

// AgentStatus defines model for AgentStatus.
type AgentStatus struct {
	ConsoleConnection struct {
		// Error Connection error description
		Error *string `json:"error,omitempty"`

		// Status Current console connection status
		Status AgentStatusConsoleConnectionStatus `json:"status"`
	} `json:"consoleConnection"`

	// Mode Target mode for the agent
	Mode AgentStatusMode `json:"mode"`
}

// AgentStatusConsoleConnectionStatus Current console connection status
type AgentStatusConsoleConnectionStatus string

// AgentStatusMode Target mode for the agent
type AgentStatusMode string

// ApplicationListResponse defines model for ApplicationListResponse.
type ApplicationListResponse struct {
	Applications []ApplicationOverview `json:"applications"`
}

// ApplicationOverview defines model for ApplicationOverview.
type ApplicationOverview struct {
	// Description Application description
	Description string `json:"description"`

	// Name Application name
	Name string `json:"name"`

	// VmCount Number of VMs running this application
	VmCount int             `json:"vmCount"`
	Vms     []ApplicationVM `json:"vms"`
}

// ApplicationVM defines model for ApplicationVM.
type ApplicationVM struct {
	// Id VM ID
	Id string `json:"id"`

	// Name VM name
	Name string `json:"name"`
}

// BatchUpdateExclusionRequest defines model for BatchUpdateExclusionRequest.
type BatchUpdateExclusionRequest struct {
	// MigrationExcluded Exclusion state to set for all VMs
	MigrationExcluded bool `json:"migrationExcluded"`

	// VmIds VM IDs to update
	VmIds []string `binding:"required,min=1,dive,required" json:"vmIds"`
}

// BenchmarkRun defines model for BenchmarkRun.
type BenchmarkRun struct {
	CreatedAt       time.Time `json:"createdAt"`
	DiskSizeGb      int       `json:"diskSizeGb"`
	DurationSec     float64   `json:"durationSec"`
	Error           *string   `json:"error,omitempty"`
	Id              int64     `json:"id"`
	Iteration       int       `json:"iteration"`
	Method          string    `json:"method"`
	PairName        string    `json:"pairName"`
	PrepDurationSec *float64  `json:"prepDurationSec,omitempty"`
	SessionId       int64     `json:"sessionId"`
	SourceDatastore string    `json:"sourceDatastore"`
	TargetDatastore string    `json:"targetDatastore"`
	ThroughputMBps  float64   `json:"throughputMBps"`
}

// CapabilityStatus defines model for CapabilityStatus.
type CapabilityStatus struct {
	Capabilities struct {
		Collector  OperationCapability `json:"collector"`
		Forecaster OperationCapability `json:"forecaster"`
		Inspector  OperationCapability `json:"inspector"`
	} `json:"capabilities"`
}

// Collection defines model for Collection.
type Collection struct {
	// CreatedAt When the collection was created
	CreatedAt time.Time `json:"createdAt"`

	// Id Collection identifier
	Id string `json:"id"`

	// Name Collection name
	Name string `json:"name"`
}

// CollectionAggregate defines model for CollectionAggregate.
type CollectionAggregate struct {
	// Clusters Number of distinct clusters
	Clusters int `json:"clusters"`

	// CreatedAt When the collection was created
	CreatedAt time.Time `json:"createdAt"`

	// Id Collection identifier
	Id string `json:"id"`

	// Migratable Number of migratable VMs (no Critical concerns)
	Migratable int `json:"migratable"`

	// NonMigratable Number of non-migratable VMs (at least one Critical concern)
	NonMigratable int `json:"nonMigratable"`

	// TotalVMs Total number of VMs in the collection
	TotalVMs int `json:"totalVMs"`
}

// CollectionComparisonDiff defines model for CollectionComparisonDiff.
type CollectionComparisonDiff struct {
	// Dimension The dimension being compared
	Dimension CollectionComparisonDiffDimension `json:"dimension"`
	OnlyInA   ComparisonDiffPage                `json:"onlyInA"`
	OnlyInB   ComparisonDiffPage                `json:"onlyInB"`
}

// CollectionComparisonDiffDimension The dimension being compared
type CollectionComparisonDiffDimension string

// CollectionComparisonSummary defines model for CollectionComparisonSummary.
type CollectionComparisonSummary struct {
	// Collections Aggregates for both collections. Index 0 is A (baseline), index 1 is B.
	Collections []CollectionAggregate `json:"collections"`

	// Diff Numeric differences (B minus A) with symmetric set-diff counts per dimension. clusters has no onlyInA/onlyInB.
	Diff struct {
		Clusters      ComparisonDiffEntry `json:"clusters"`
		Migratable    ComparisonDiffEntry `json:"migratable"`
		NonMigratable ComparisonDiffEntry `json:"nonMigratable"`
		TotalVMs      ComparisonDiffEntry `json:"totalVMs"`
	} `json:"diff"`
}

// CollectionListResponse defines model for CollectionListResponse.
type CollectionListResponse struct {
	Collections []Collection `json:"collections"`
}

// CollectorStatus defines model for CollectorStatus.
type CollectorStatus struct {
	// Error Error message when status is error
	Error  *string               `json:"error,omitempty"`
	Status CollectorStatusStatus `json:"status"`
}

// CollectorStatusStatus defines model for CollectorStatus.Status.
type CollectorStatusStatus string

// ComparisonDiffEntry defines model for ComparisonDiffEntry.
type ComparisonDiffEntry struct {
	// Delta Difference (B minus A). Positive means B has more.
	Delta int `json:"delta"`

	// OnlyInA Count of VMs satisfying this dimension in A but not in B
	OnlyInA *int `json:"onlyInA,omitempty"`

	// OnlyInB Count of VMs satisfying this dimension in B but not in A
	OnlyInB *int `json:"onlyInB,omitempty"`
}

// ComparisonDiffPage defines model for ComparisonDiffPage.
type ComparisonDiffPage struct {
	// Page Current page number
	Page int `json:"page"`

	// PageCount Total number of pages
	PageCount int `json:"pageCount"`

	// Total Total number of VM IDs in this list
	Total int `json:"total"`

	// VmIds VM IDs on this page. Empty array when page exceeds pageCount.
	VmIds []string `json:"vmIds"`
}

// CreateGroupRequest defines model for CreateGroupRequest.
type CreateGroupRequest struct {
	Description *string `binding:"omitempty,max=500" json:"description,omitempty"`
	Filter      string  `binding:"required,min=1" json:"filter"`
	Name        string  `binding:"required,min=1,max=100" json:"name"`
}

// CredentialStatus defines model for CredentialStatus.
type CredentialStatus struct {
	// Url vCenter URL the credentials belong to
	Url string `json:"url"`

	// Username vCenter username
	Username string `json:"username"`

	// Valid Whether credentials are stored for the returned URL.
	Valid bool `json:"valid"`
}

// DatastoreDetail defines model for DatastoreDetail.
type DatastoreDetail struct {
	Capabilities   *[]string `json:"capabilities,omitempty"`
	CapacityGb     float64   `json:"capacityGb"`
	FreeGb         float64   `json:"freeGb"`
	NaaDevices     *[]string `json:"naaDevices,omitempty"`
	Name           string    `json:"name"`
	StorageArrayId *string   `json:"storageArrayId,omitempty"`
	StorageModel   *string   `json:"storageModel,omitempty"`
	StorageVendor  *string   `json:"storageVendor,omitempty"`

	// Type VMFS, NFS, VVol, or OTHER
	Type string `json:"type"`
}

// DatastorePairRequest defines model for DatastorePairRequest.
type DatastorePairRequest struct {
	Host            *string `json:"host,omitempty"`
	Name            string  `json:"name"`
	SourceDatastore string  `json:"sourceDatastore"`
	TargetDatastore string  `json:"targetDatastore"`
}

// DeleteLabelGloballyResponse defines model for DeleteLabelGloballyResponse.
type DeleteLabelGloballyResponse struct {
	// Affected Number of VMs that had the label removed
	Affected int `json:"affected"`

	// Label The label that was removed
	Label string `json:"label"`
}

// EstimateRange defines model for EstimateRange.
type EstimateRange struct {
	// BestCase Duration string (e.g. "1h30m")
	BestCase string `json:"bestCase"`

	// Expected Duration string (e.g. "2h15m")
	Expected string `json:"expected"`

	// WorstCase Duration string (e.g. "3h45m")
	WorstCase string `json:"worstCase"`
}

// ForecastPairStatus defines model for ForecastPairStatus.
type ForecastPairStatus struct {
	CompletedRuns     int                     `json:"completedRuns"`
	Error             *string                 `json:"error,omitempty"`
	Host              *string                 `json:"host,omitempty"`
	PairName          string                  `json:"pairName"`
	PrepBytesTotal    *int64                  `json:"prepBytesTotal,omitempty"`
	PrepBytesUploaded *int64                  `json:"prepBytesUploaded,omitempty"`
	SourceDatastore   string                  `json:"sourceDatastore"`
	State             ForecastPairStatusState `json:"state"`
	TargetDatastore   string                  `json:"targetDatastore"`
	TotalRuns         int                     `json:"totalRuns"`
}

// ForecastPairStatusState defines model for ForecastPairStatus.State.
type ForecastPairStatusState string

// ForecastStats defines model for ForecastStats.
type ForecastStats struct {
	Ci95Lower   float64       `json:"ci95Lower"`
	Ci95Upper   float64       `json:"ci95Upper"`
	EstPer1TB   EstimateRange `json:"estPer1TB"`
	MaxMBps     float64       `json:"maxMBps"`
	MeanMBps    float64       `json:"meanMBps"`
	MedianMBps  float64       `json:"medianMBps"`
	MinMBps     float64       `json:"minMBps"`
	PairName    string        `json:"pairName"`
	SampleCount int           `json:"sampleCount"`
	StdDevMBps  float64       `json:"stdDevMBps"`
}

// ForecasterStatus defines model for ForecasterStatus.
type ForecasterStatus struct {
	Pairs []ForecastPairStatus  `json:"pairs"`
	State ForecasterStatusState `json:"state"`
}

// ForecasterStatusState defines model for ForecasterStatus.State.
type ForecasterStatusState string

// Group defines model for Group.
type Group struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Description Optional group description
	Description *string `json:"description,omitempty"`

	// Filter Filter expression (pkg/filter DSL)
	Filter string `json:"filter"`

	// Id Unique group identifier
	Id string `json:"id"`

	// Name Group display name
	Name      string     `json:"name"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`

	// VmCount Number of VMs matching the group filter
	VmCount *int `json:"vmCount,omitempty"`
}

// GroupListResponse defines model for GroupListResponse.
type GroupListResponse struct {
	Groups    []Group `json:"groups"`
	Page      int     `json:"page"`
	PageCount int     `json:"pageCount"`
	Total     int     `json:"total"`
}

// GroupResponse defines model for GroupResponse.
type GroupResponse struct {
	Group     Group                   `json:"group"`
	Inventory *externalRef0.Inventory `json:"inventory,omitempty"`
	Page      int                     `json:"page"`
	PageCount int                     `json:"pageCount"`
	Total     int                     `json:"total"`
	Vms       []VirtualMachine        `json:"vms"`
}

// GuestNetwork defines model for GuestNetwork.
type GuestNetwork struct {
	// Device Network device name inside the guest
	Device *string `json:"device,omitempty"`

	// Ip IP address
	Ip *string `json:"ip,omitempty"`

	// Mac MAC address as seen by the guest
	Mac *string `json:"mac,omitempty"`

	// Network Network name from the guest
	Network *string `json:"network,omitempty"`

	// PrefixLength Network prefix length (CIDR)
	PrefixLength *int32 `json:"prefixLength,omitempty"`
}

// InspectionStatus defines model for InspectionStatus.
type InspectionStatus struct {
	// Details Human-readable details about the current inspection state
	Details *string `json:"details,omitempty"`

	// Error Error message when state is error
	Error *string `json:"error,omitempty"`

	// State Current inspection state
	State InspectionStatusState `json:"state"`
}

// InspectionStatusState Current inspection state
type InspectionStatusState string

// InspectorStatus defines model for InspectorStatus.
type InspectorStatus struct {
	// State Inspector state
	State InspectorStatusState `json:"state"`
	Vddk  *VddkProperties      `json:"vddk,omitempty"`
}

// InspectorStatusState Inspector state
type InspectorStatusState string

// Inventory defines model for Inventory.
type Inventory struct {
	Inventory externalRef0.UpdateInventory `json:"inventory"`
}

// OperationCapability defines model for OperationCapability.
type OperationCapability struct {
	// Enabled Whether stored credentials have sufficient privileges
	Enabled bool `json:"enabled"`

	// MissingPrivileges Specific vSphere privileges that are missing
	MissingPrivileges *[]string `json:"missingPrivileges,omitempty"`
}

// PairCapability defines model for PairCapability.
type PairCapability struct {
	Capabilities    []string `json:"capabilities"`
	PairName        string   `json:"pairName"`
	SourceDatastore string   `json:"sourceDatastore"`
	TargetDatastore string   `json:"targetDatastore"`
}

// PairCapabilityRequest defines model for PairCapabilityRequest.
type PairCapabilityRequest struct {
	Pairs []DatastorePairRequest `json:"pairs"`
}

// Process defines model for Process.
type Process struct {
	// Name Name of the process
	Name string `json:"name"`

	// Version Version of the process
	Version *string `json:"version,omitempty"`
}

// RightsizingClusterResponse defines model for RightsizingClusterResponse.
type RightsizingClusterResponse struct {
	Cluster  RightsizingClusterUtilization `json:"cluster"`
	ReportId string                        `json:"report_id"`
}

// RightsizingClusterUtilization defines model for RightsizingClusterUtilization.
type RightsizingClusterUtilization struct {
	ClusterId                string  `json:"cluster_id"`
	ClusterName              string  `json:"cluster_name"`
	Confidence               float64 `json:"confidence"`
	CpuAvg                   float64 `json:"cpu_avg"`
	CpuMax                   float64 `json:"cpu_max"`
	CpuP95                   float64 `json:"cpu_p95"`
	Disk                     float64 `json:"disk"`
	MemAvg                   float64 `json:"mem_avg"`
	MemMax                   float64 `json:"mem_max"`
	MemP95                   float64 `json:"mem_p95"`
	TotalProvisionedCpus     int     `json:"total_provisioned_cpus"`
	TotalProvisionedDiskKb   float64 `json:"total_provisioned_disk_kb"`
	TotalProvisionedMemoryMb int     `json:"total_provisioned_memory_mb"`
	VmCount                  int     `json:"vm_count"`
}

// StartForecasterRequest defines model for StartForecasterRequest.
type StartForecasterRequest struct {
	Concurrency *int                   `json:"concurrency,omitempty"`
	DiskSizeGb  *int                   `json:"diskSizeGb,omitempty"`
	Iterations  *int                   `json:"iterations,omitempty"`
	Pairs       []DatastorePairRequest `json:"pairs"`
}

// StartInspectionRequest defines model for StartInspectionRequest.
type StartInspectionRequest struct {
	// VmIds VM MoRef IDs to inspect
	VmIds []string `binding:"required,min=1,dive,required" json:"vmIds"`
}

// UpdateGroupRequest defines model for UpdateGroupRequest.
type UpdateGroupRequest struct {
	Description *string `binding:"omitempty,max=500" json:"description,omitempty"`
	Filter      *string `binding:"omitempty,min=1" json:"filter,omitempty"`
	Name        *string `binding:"omitempty,min=1,max=100" json:"name,omitempty"`
}

// UpdateLabelVMsRequest defines model for UpdateLabelVMsRequest.
type UpdateLabelVMsRequest struct {
	// Add VMs to add the label to
	Add *[]string `binding:"omitempty,dive,required" json:"add,omitempty"`

	// Remove VMs to remove the label from
	Remove *[]string `binding:"omitempty,dive,required" json:"remove,omitempty"`
}

// VMFilterOptionsResponse defines model for VMFilterOptionsResponse.
type VMFilterOptionsResponse struct {
	// Applications Distinct detected application names
	Applications []string `json:"applications"`

	// Clusters Distinct cluster names
	Clusters []string `json:"clusters"`

	// ConcernCategories Distinct concern categories
	ConcernCategories []string `json:"concernCategories"`

	// ConcernLabels Distinct concern labels
	ConcernLabels []string `json:"concernLabels"`

	// Datacenters Distinct datacenter names
	Datacenters []string `json:"datacenters"`
}

// VMLabelsResponse defines model for VMLabelsResponse.
type VMLabelsResponse struct {
	// Counts Number of VMs with each label (same order as labels array)
	Counts []int `json:"counts"`

	// Labels Distinct labels currently in use
	Labels []string `json:"labels"`
}

// VcenterCredentials defines model for VcenterCredentials.
type VcenterCredentials struct {
	// Cacert PEM-encoded CA certificate bundle for verifying the vCenter TLS certificate. Mutually exclusive with skipTls.
	Cacert   *string `binding:"omitempty" json:"cacert,omitempty"`
	Password string  `binding:"required,min=1" json:"password"`

	// SkipTls When true, TLS certificate verification is skipped. Must not be set to true alongside cacert — that combination returns 400. When omitted: if cacert is absent the connection skips TLS verification (backwards compatibility); if cacert is provided the connection verifies TLS using that certificate — skipTls need not be sent.
	SkipTls *bool `json:"skipTls,omitempty"`

	// Url vCenter URL
	Url      string `binding:"required,url" json:"url"`
	Username string `binding:"required,min=1" json:"username"`
}

// VddkProperties defines model for VddkProperties.
type VddkProperties struct {
	Bytes *int64 `json:"bytes,omitempty"`

	// Md5 md5 sum of the uploaded tarball
	Md5 string `json:"md5"`

	// Version The matching vSphere Client version
	Version string `json:"version"`
}

// VersionInfo defines model for VersionInfo.
type VersionInfo struct {
	// GitCommit Git commit SHA
	GitCommit string `json:"gitCommit"`

	// UiGitCommit UI git commit SHA
	UiGitCommit string `json:"uiGitCommit"`

	// Version Agent version
	Version string `json:"version"`
}

// VirtualMachine defines model for VirtualMachine.
type VirtualMachine struct {
	// Cluster Cluster name
	Cluster string `json:"cluster"`

	// Datacenter Datacenter name
	Datacenter string `json:"datacenter"`

	// DiskSize Total disk size in MB
	DiskSize int64 `json:"diskSize"`

	// Groups Names of groups this VM matches
	Groups *[]string `json:"groups,omitempty"`

	// Id VirtualMachine ID in vCenter
	Id string `json:"id"`

	// InspectionConcernCount Number of inspection concerns for the latest persisted result
	InspectionConcernCount *int              `json:"inspectionConcernCount,omitempty"`
	InspectionStatus       *InspectionStatus `json:"inspectionStatus,omitempty"`

	// IssueCount Number of issues found for this VirtualMachine
	IssueCount int `json:"issueCount"`

	// Labels User-defined labels for this VM
	Labels *[]string `binding:"omitempty,dive,min=1,max=100" json:"labels,omitempty"`

	// Memory Memory size in MB
	Memory int64 `json:"memory"`

	// Migratable True if the VirtualMachine is migratable for MTV
	Migratable *bool `json:"migratable,omitempty"`

	// MigrationExcluded Whether this VM is excluded from migration
	MigrationExcluded *bool `json:"migrationExcluded,omitempty"`

	// Name VirtualMachine name
	Name string `json:"name"`

	// Template True if the VirtualMachine is a template
	Template *bool `json:"template,omitempty"`

	// UtilizationConfidence Data confidence -- sample_count / expected_sample_count x 100
	UtilizationConfidence *float64 `json:"utilization_confidence,omitempty"`

	// UtilizationCpuMax CPU utilization at max (%); absent when no utilization data
	UtilizationCpuMax *float64 `json:"utilization_cpu_max,omitempty"`

	// UtilizationCpuP95 CPU utilization at p95 (%); absent when no utilization data
	UtilizationCpuP95 *float64 `json:"utilization_cpu_p95,omitempty"`

	// UtilizationDisk Disk utilization (%); absent when no utilization data
	UtilizationDisk *float64 `json:"utilization_disk,omitempty"`

	// UtilizationMemMax Memory utilization at max (%); absent when no utilization data
	UtilizationMemMax *float64 `json:"utilization_mem_max,omitempty"`

	// UtilizationMemP95 Memory utilization at p95 (%); absent when no utilization data
	UtilizationMemP95 *float64 `json:"utilization_mem_p95,omitempty"`

	// VCenterID Identifier of the vCenter this VirtualMachine belongs to
	VCenterID string `json:"vCenterID"`

	// VCenterState vCenter state (e.g., poweredOn, poweredOff, suspended)
	VCenterState string `json:"vCenterState"`
}

// VirtualMachineDetail defines model for VirtualMachineDetail.
type VirtualMachineDetail struct {
	// Cluster Cluster name
	Cluster *string `json:"cluster,omitempty"`

	// ConnectionState Connection state (connected, disconnected, orphaned, inaccessible)
	ConnectionState string `json:"connectionState"`

	// CoresPerSocket CPU cores per virtual socket
	CoresPerSocket int32 `json:"coresPerSocket"`

	// CpuAffinity Physical CPU IDs the VirtualMachine is pinned to
	CpuAffinity *[]int32 `json:"cpuAffinity,omitempty"`

	// CpuCount Total virtual CPUs
	CpuCount int32 `json:"cpuCount"`

	// Datacenter Datacenter name
	Datacenter *string                 `json:"datacenter,omitempty"`
	Devices    *[]VirtualMachineDevice `json:"devices,omitempty"`
	Disks      []VirtualMachineDisk    `json:"disks"`

	// FaultToleranceEnabled Whether Fault Tolerance is enabled
	FaultToleranceEnabled *bool `json:"faultToleranceEnabled,omitempty"`

	// Firmware Firmware type (bios or efi)
	Firmware *string `json:"firmware,omitempty"`

	// Folder Inventory folder reference
	Folder *string `json:"folder,omitempty"`

	// GuestId VMware guest OS identifier
	GuestId *string `json:"guestId,omitempty"`

	// GuestName Guest OS full name
	GuestName     *string         `json:"guestName,omitempty"`
	GuestNetworks *[]GuestNetwork `json:"guestNetworks,omitempty"`

	// Host ESXi host reference
	Host *string `json:"host,omitempty"`

	// HostName Guest hostname
	HostName *string `json:"hostName,omitempty"`

	// Id Unique identifier for the VirtualMachine in vCenter
	Id string `json:"id"`

	// Inspection VirtualMachines Inspection results
	Inspection       *VirtualMachineInspectionResults `json:"inspection,omitempty"`
	InspectionStatus *InspectionStatus                `json:"inspectionStatus,omitempty"`

	// IpAddress Guest primary IP address
	IpAddress *string                `json:"ipAddress,omitempty"`
	Issues    *[]VirtualMachineIssue `json:"issues,omitempty"`

	// Labels User-defined labels for this VM
	Labels *[]string `binding:"omitempty,dive,min=1,max=100" json:"labels,omitempty"`

	// MemoryMB Memory in megabytes
	MemoryMB int32 `json:"memoryMB"`

	// Migratable Whether the VirtualMachine can be migrated
	Migratable *bool `json:"migratable,omitempty"`

	// MigrationExcluded Whether this VM is excluded from migration
	MigrationExcluded *bool `json:"migrationExcluded,omitempty"`

	// Name Display name of the VirtualMachine
	Name string `json:"name"`

	// NestedHVEnabled Whether nested virtualization is enabled
	NestedHVEnabled *bool               `json:"nestedHVEnabled,omitempty"`
	Nics            []VirtualMachineNIC `json:"nics"`

	// PowerState Current power state (poweredOn, poweredOff, suspended)
	PowerState string `json:"powerState"`

	// Processes List of processes detected on this VM
	Processes *[]Process `json:"processes,omitempty"`

	// StorageUsed Storage consumed in bytes
	StorageUsed *int64 `json:"storageUsed,omitempty"`

	// Template Whether the VirtualMachine is a template
	Template *bool `json:"template,omitempty"`

	// ToolsRunningStatus Whether VMware Tools is running
	ToolsRunningStatus *string `json:"toolsRunningStatus,omitempty"`

	// ToolsStatus VMware Tools installation status
	ToolsStatus *string               `json:"toolsStatus,omitempty"`
	Utilization *VmUtilizationDetails `json:"utilization,omitempty"`

	// Uuid Universally unique identifier assigned by vCenter
	Uuid *string `json:"uuid,omitempty"`

	// VCenterID Identifier of the vCenter this VirtualMachine belongs to
	VCenterID string `json:"vCenterID"`
}

// VirtualMachineDevice defines model for VirtualMachineDevice.
type VirtualMachineDevice struct {
	// Kind Device type (cdrom, floppy, usb, serial, parallel)
	Kind *string `json:"kind,omitempty"`
}

// VirtualMachineDisk defines model for VirtualMachineDisk.
type VirtualMachineDisk struct {
	// Bus Bus type (scsi, ide, sata, nvme)
	Bus *string `json:"bus,omitempty"`

	// Capacity Disk capacity in bytes
	Capacity *int64 `json:"capacity,omitempty"`

	// File VMDK file path in the datastore
	File *string `json:"file,omitempty"`

	// Key Unique disk key within the VirtualMachine
	Key *int32 `json:"key,omitempty"`

	// Mode Disk mode (persistent, independent_persistent, independent_nonpersistent)
	Mode *string `json:"mode,omitempty"`

	// Rdm Whether this is a Raw Device Mapping
	Rdm *bool `json:"rdm,omitempty"`

	// Shared Whether the disk is shared between multiple VirtualMachines
	Shared *bool `json:"shared,omitempty"`
}

// VirtualMachineInspectionConcern defines model for VirtualMachineInspectionConcern.
type VirtualMachineInspectionConcern struct {
	Category string `json:"category"`

	// Label Short label identifying the concern
	Label   string `json:"label"`
	Message string `json:"message"`
}

// VirtualMachineInspectionResults VirtualMachines Inspection results
type VirtualMachineInspectionResults struct {
	Concerns *[]VirtualMachineInspectionConcern `json:"concerns,omitempty"`
}

// VirtualMachineIssue defines model for VirtualMachineIssue.
type VirtualMachineIssue struct {
	Category VirtualMachineIssueCategory `json:"category"`

	// Description Detailed description with context and recommendations
	Description string `json:"description"`

	// Label Short label
	Label string `json:"label"`
}

// VirtualMachineIssueCategory defines model for VirtualMachineIssue.Category.
type VirtualMachineIssueCategory string

// VirtualMachineListResponse defines model for VirtualMachineListResponse.
type VirtualMachineListResponse struct {
	// Page Current page number
	Page int `json:"page"`

	// PageCount Total number of pages
	PageCount int `json:"pageCount"`

	// Total Total number of VirtualMachines matching the filter
	Total           int              `json:"total"`
	VirtualMachines []VirtualMachine `json:"virtualMachines"`
}

// VirtualMachineNIC defines model for VirtualMachineNIC.
type VirtualMachineNIC struct {
	// Index NIC index within the VirtualMachine
	Index *int `json:"index,omitempty"`

	// Mac MAC address
	Mac *string `json:"mac,omitempty"`

	// Network Network reference
	Network *string `json:"network,omitempty"`
}

// VirtualMachineUpdateRequest defines model for VirtualMachineUpdateRequest.
type VirtualMachineUpdateRequest struct {
	// Labels User-defined labels (replaces existing labels)
	Labels *[]string `binding:"omitempty,dive,notblank,min=1,max=100" json:"labels,omitempty"`

	// MigrationExcluded Whether to exclude this VM from migration
	MigrationExcluded *bool `binding:"omitempty" json:"migrationExcluded,omitempty"`
}

// VmUtilizationDetails defines model for VmUtilizationDetails.
type VmUtilizationDetails struct {
	Confidence          float64 `json:"confidence"`
	CpuAvg              float64 `json:"cpu_avg"`
	CpuLatest           float64 `json:"cpu_latest"`
	CpuMax              float64 `json:"cpu_max"`
	CpuP95              float64 `json:"cpu_p95"`
	Disk                float64 `json:"disk"`
	MemAvg              float64 `json:"mem_avg"`
	MemLatest           float64 `json:"mem_latest"`
	MemMax              float64 `json:"mem_max"`
	MemP95              float64 `json:"mem_p95"`
	Moid                string  `json:"moid"`
	ProvisionedCpus     int     `json:"provisioned_cpus"`
	ProvisionedDiskKb   float64 `json:"provisioned_disk_kb"`
	ProvisionedMemoryMb int     `json:"provisioned_memory_mb"`
	VmName              string  `json:"vm_name"`
}

// CompareCollectionsDiffParams defines parameters for CompareCollectionsDiff.
type CompareCollectionsDiffParams struct {
	// Page Page number (1-based). Applied independently to onlyInA and onlyInB.
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of VM IDs per page per side
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// CompareCollectionsDiffParamsDimension defines parameters for CompareCollectionsDiff.
type CompareCollectionsDiffParamsDimension string

// ExportCollectionParams defines parameters for ExportCollection.
type ExportCollectionParams struct {
	// Scope Comma-separated export scopes (e.g., "overview,vms,groups"). Defaults to "overview".
	Scope *string `form:"scope,omitempty" json:"scope,omitempty"`

	// Format Output format: zip (CSV files in a ZIP archive) or xlsx (Excel workbook with one sheet per scope)
	Format *ExportCollectionParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// ExportCollectionParamsFormat defines parameters for ExportCollection.
type ExportCollectionParamsFormat string

// ListGroupsParams defines parameters for ListGroups.
type ListGroupsParams struct {
	// ByName Filter groups by name (case-insensitive substring match)
	ByName *string `form:"byName,omitempty" json:"byName,omitempty"`

	// Page Page number (1-indexed)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of groups per page
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetGroupParams defines parameters for GetGroup.
type GetGroupParams struct {
	// Sort Sort fields with direction (e.g., "name:asc", "cluster:desc"). Valid fields are name, vCenterState, cluster, diskSize, memory, issues, cpuUsage, diskUsage, ramUsage, cpuAvg, memAvg.
	Sort *[]string `form:"sort,omitempty" json:"sort,omitempty"`

	// Page Page number for pagination
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// ListVirtualMachinesParams defines parameters for ListVirtualMachines.
type ListVirtualMachinesParams struct {
	// ByExpression Filter by expression
	ByExpression *string `form:"byExpression,omitempty" json:"byExpression,omitempty"`

	// Sort Sort fields with direction (e.g., "name:asc", "cluster:desc"). Valid fields are name, vCenterState, cluster, diskSize, memory, issues, cpuUsage, diskUsage, ramUsage, cpuAvg, memAvg.
	Sort *[]string `form:"sort,omitempty" json:"sort,omitempty"`

	// Page Page number for pagination
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetForecasterRunsParams defines parameters for GetForecasterRuns.
type GetForecasterRunsParams struct {
	// PairName Filter runs by pair name
	PairName *string `form:"pairName,omitempty" json:"pairName,omitempty"`
}

// GetForecasterStatsParams defines parameters for GetForecasterStats.
type GetForecasterStatsParams struct {
	// PairName Pair name to get statistics for
	PairName string `form:"pairName" json:"pairName"`
}

// ListLatestGroupsParams defines parameters for ListLatestGroups.
type ListLatestGroupsParams struct {
	// ByName Filter groups by name (case-insensitive substring match)
	ByName *string `form:"byName,omitempty" json:"byName,omitempty"`

	// Page Page number (1-indexed)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of groups per page
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetLatestGroupParams defines parameters for GetLatestGroup.
type GetLatestGroupParams struct {
	// Sort Sort fields with direction (e.g., "name:asc", "cluster:desc"). Valid fields are name, vCenterState, cluster, diskSize, memory, issues, cpuUsage, diskUsage, ramUsage, cpuAvg, memAvg.
	Sort *[]string `form:"sort,omitempty" json:"sort,omitempty"`

	// Page Page number for pagination
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetInspectorStatusParams defines parameters for GetInspectorStatus.
type GetInspectorStatusParams struct {
	// IncludeVddk Include VDDK metadata in the response
	IncludeVddk *bool `form:"includeVddk,omitempty" json:"includeVddk,omitempty"`
}

// PutInspectorVddkMultipartBody defines parameters for PutInspectorVddk.
type PutInspectorVddkMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// GetLatestInventoryParams defines parameters for GetLatestInventory.
type GetLatestInventoryParams struct {
	// Scope Selects which inventories to return. "main" (default) returns only the main inventory as JSON. "all" returns a ZIP bundle containing the main inventory (inventory.json) and every group subset inventory (subsets/<groupId>.json), for manual upload in disconnected environments.
	Scope *GetLatestInventoryParamsScope `form:"scope,omitempty" json:"scope,omitempty"`
}

// GetLatestInventoryParamsScope defines parameters for GetLatestInventory.
type GetLatestInventoryParamsScope string

// ListLatestVirtualMachinesParams defines parameters for ListLatestVirtualMachines.
type ListLatestVirtualMachinesParams struct {
	// ByExpression Filter by expression
	ByExpression *string `form:"byExpression,omitempty" json:"byExpression,omitempty"`

	// Sort Sort fields with direction (e.g., "name:asc", "cluster:desc"). Valid fields are name, vCenterState, cluster, diskSize, memory, issues, cpuUsage, diskUsage, ramUsage, cpuAvg, memAvg.
	Sort *[]string `form:"sort,omitempty" json:"sort,omitempty"`

	// Page Page number for pagination
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// SetAgentModeJSONRequestBody defines body for SetAgentMode for application/json ContentType.
type SetAgentModeJSONRequestBody = AgentModeRequest

// PutCredentialsJSONRequestBody defines body for PutCredentials for application/json ContentType.
type PutCredentialsJSONRequestBody = VcenterCredentials

// StartForecasterJSONRequestBody defines body for StartForecaster for application/json ContentType.
type StartForecasterJSONRequestBody = StartForecasterRequest

// PostForecasterPairCapabilitiesJSONRequestBody defines body for PostForecasterPairCapabilities for application/json ContentType.
type PostForecasterPairCapabilitiesJSONRequestBody = PairCapabilityRequest

// CreateLatestGroupJSONRequestBody defines body for CreateLatestGroup for application/json ContentType.
type CreateLatestGroupJSONRequestBody = CreateGroupRequest

// UpdateLatestGroupJSONRequestBody defines body for UpdateLatestGroup for application/json ContentType.
type UpdateLatestGroupJSONRequestBody = UpdateGroupRequest

// StartInspectionJSONRequestBody defines body for StartInspection for application/json ContentType.
type StartInspectionJSONRequestBody = StartInspectionRequest

// PutInspectorVddkMultipartRequestBody defines body for PutInspectorVddk for multipart/form-data ContentType.
type PutInspectorVddkMultipartRequestBody PutInspectorVddkMultipartBody

// BatchUpdateLatestVMExclusionJSONRequestBody defines body for BatchUpdateLatestVMExclusion for application/json ContentType.
type BatchUpdateLatestVMExclusionJSONRequestBody = BatchUpdateExclusionRequest

// UpdateLatestLabelVMsJSONRequestBody defines body for UpdateLatestLabelVMs for application/json ContentType.
type UpdateLatestLabelVMsJSONRequestBody = UpdateLabelVMsRequest

// UpdateLatestVirtualMachineJSONRequestBody defines body for UpdateLatestVirtualMachine for application/json ContentType.
type UpdateLatestVirtualMachineJSONRequestBody = VirtualMachineUpdateRequest
